### ISSUE TITLE
Can NOT package to EXE

### ISSUE THREAD

**Issue by bgbg108555** [ruyo/VRM4U#1]
hi Ruyo it's very cool work. But,

include VRM4U plugin in UE4, than package will get this error:

Could not find definition for module 'VRM4U' (referenced via default plugins -> VRM4U.uplugin)	MVN_4222	D:\Unreal\MVN_4222\Intermediate\ProjectFiles\UnrealBuildTool	1

any Suggest or supported

**Comment by ruyo** [comment]
Please use source repository from https://github.com/ruyo/UnrealEngine_VRM4UPlugin
(If you could not find this page, try https://www.unrealengine.com/en-US/ue4-on-github)

Maybe some blueprints will get error, please remove those files. They are unnecessary files for package.
(e.g., DropActor, MToonActorLeap...)

Thanks.

**Comment by bgbg108555** [comment]
Thanks very much

**Comment by ruyo** [comment]
Welcome.
