### ISSUE TITLE
"ISO C++ forbids forward references to 'enum' types Plugins\VRM4U\Source\VRM4U\Public\VrmCameraCheckComponent.h 45" when building Server for Linux with WSL

### ISSUE THREAD

**Issue by Shoop123** [ruyo/VRM4U#119]
![image](https://user-images.githubusercontent.com/8333998/150281837-10135bb8-ca1b-49ca-84a7-e477be2044c4.png)

Following errors appear after trying to build for Linux Server with WSL. Builds for Windows perfectly, but a Linux build is significantly cheaper.

`1>    Plugins\VRM4U\Source\VRM4U\Public\VrmCameraCheckComponent.h(45,70): error : ISO C++ forbids forward references to 'enum' types
1>              void OnCameraTransformChanged(const FVector&, const FRotator&, enum ELevelViewportType, int32);`

`Plugins\VRM4U\Source\VRM4U\Public\VrmCameraCheckComponent.h(45,70): error : ISO C++ forbids forward references to 'enum' types
1>              void OnCameraTransformChanged(const FVector&, const FRotator&, enum ELevelViewportType, int32);`

`Plugins\VRM4U\Source\VRM4U\Private\VrmCameraCheckComponent.cpp(26,108): error : variable has incomplete type 'ELevelViewportType'
1>      void UVrmCameraCheckComponent::OnCameraTransformChanged(const FVector&, const FRotator&, ELevelViewportType, int32) {`

Any suggestions welcome!

**Comment by ruyo** [comment]
Hi.
Fixed an error in building the Linux Game. Please get the latest source files.
I have not tested it. Please let me know if there are any problems.

thanks.

**Comment by Shoop123** [comment]
Yup, seems like it fixed those. New one appeared:

`#pragma once in main file [-Werror,-Wpragma-once-outside-header] Plugins\VRM4U\Source\VRM4U\Private\VrmUtilImage.cpp	3	
`

**Comment by ruyo** [comment]
Please download the source again and try again.
I have fixed the error in various build types. If you still get the error, please let me know what build configuration you are using.
thanks

**Comment by Shoop123** [comment]
Works like a charm! Thanks a ton!
