### ISSUE TITLE
Unable to package the game, compile errors.

### ISSUE THREAD

**Issue by Ethan3481** [ruyo/VRM4U#124]
Hey,

I have been having a hard time packaging my game on Unreal Engine 5. Everything seems to work for me without any issues but the moment I try to package the game, I get compilation errors. 

**Log file**: https://drive.google.com/file/d/1qHjM7XoJ45vUPbQo8Y_A0jtrI5w9TG2a/view?usp=sharing
**The errors I'm getting** :-

PackagingResults: Error: Expecting to find a type to be declared in a module rules named 'VRM4U' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.

PackagingResults: Error: Expecting to find a type to be declared in a module rules named 'VRM4U' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.

UnrealEngine Version: UE5

**Additional information**:-
For disclosure, I have already been through the video that was suggested in one of the issues thread earlier (https://www.youtube.com/watch?v=IoooTbQbgx4)

I'd really appreciate some help.

Sincerely,

Ethan348.

**Comment by ruyo** [comment]
Hi.
From the logs, it looks like you are using UE4.25, is that correct?

VRM4U needs to be placed in the project folder.
If you have it in the Engine folder, please move it.

**Comment by Ethan3481** [comment]
Hey,

No I'm not using UE 4.25. I'm using Unreal Engine 5.0. 
Yes, VRM4U was in the Engine folder. The thing is, I tried the method earlier where I placed the plugin in the project folder. But upon searching for the plugin in the search. It didn't show up in the Unreal Editor.

I'll give it another try, might have missed a step and let you know right away.

**Comment by Ethan3481** [comment]
@ruyo I started packaging yet again. Surprisingly, the VRM4U plugin shows up now after moving it to the project folder.

The process is currently stuck at "Checking global shaders for platform Windows", hopefully everything works out.

Thank you for your help.

**Comment by Ethan3481** [comment]
Okay, it failed after all these hours.

**Following are the errors:-**

PackagingResults: Error: [AssetLog] C:\Users\saagu\Documents\Unreal Projects\TPP_Test_2\Plugins\VRM4U\Content\Util\BaseCharacter\BP_VrmPoseCopy.uasset: [Compiler] In use pin  Src Skinned Mesh  no longer exists on node  Set Skeletal Mesh Copy Data . Please refresh node or break links to remove pin. from Source: /VRM4U/Util/BaseCharacter/BP_VrmPoseCopy.BP_VrmPoseCopy

PackagingResults: Error: [AssetLog] C:\Users\saagu\Documents\Unreal Projects\TPP_Test_2\Plugins\VRM4U\Content\Util\BaseCharacter\Misc\BP_VrmAnimControlComponent.uasset: [Compiler] The property associated with  Center Location Scale by Height Scale  could not be found in '/VRM4U/Util/BaseCharacter/Misc/BP_VrmAnimControlComponent.BP_VrmAnimControlComponent_C' from Source: /VRM4U/Util/BaseCharacter/Misc/BP_VrmAnimControlComponent.BP_VrmAnimControlComponent

PackagingResults: Error: [AssetLog] C:\Users\saagu\Documents\Unreal Projects\TPP_Test_2\Plugins\VRM4U\Content\Util\BaseCharacter\Misc\BP_VrmAnimControlComponent.uasset: [Compiler] The property associated with  Center Location Scale by Height Scale  could not be found in '/VRM4U/Util/BaseCharacter/Misc/BP_VrmAnimControlComponent.BP_VrmAnimControlComponent_C' from Source: /VRM4U/Util/BaseCharacter/Misc/BP_VrmAnimControlComponent.BP_VrmAnimControlComponent

PackagingResults: Error: UStructProperty::Serialize Loading: Property 'StructProperty /VRM4U/Util/BaseCharacter/Mesh/ABP_VRoidSimpleMannequinRetarget.ABP_VRoidSimpleMannequinRetarget_C:AnimGraphNode_VrmRetargetFromMannequin_33F75265463B715F32693E81E6865A58'. Unknown structure.

There are actually more errors, but I listed the ones relevant to the plugin.

**My Log**
https://drive.google.com/file/d/1oTObrXPPXRv_va4SLknxo8ptr-mkvUS1/view?usp=sharing

Looking forward to hearing from you.

**Comment by ruyo** [comment]
Probably due to the difference between the binary and source versions.
Please refer to this page and specify the same date as the built binary when downloading the source.
I will update the documentation.

![image](https://user-images.githubusercontent.com/6472835/151966544-02e178f0-eb8a-48e6-b9dd-bd8d2b93b39b.png)

**Comment by Ethan3481** [comment]
I just downloaded the source after following the instructions from the image above, I'll see what happens now, I'll keep you updated.

**Comment by Ethan3481** [comment]
I started a new project and the game can be packaged now. All the errors related to VRM4U are gone. 

Thank you so much for your time @ruyo.

**Comment by ruyo** [comment]
Please see the VRM4U.uplugin file.

This specification is for compatibility purposes only.
Please replace it with UncookedOnly as shown in the comments.
There are no packaging issues.

![image](https://user-images.githubusercontent.com/6472835/152200208-256df04e-3d7f-411b-9c09-80b5bea69084.png)

**Comment by Ethan3481** [comment]
Thank you so much @ruyo , seems like everything's been fixed now.
