### ISSUE TITLE
Unreal Engine 4.26.2 Can't launch in Oculus quest 2

### ISSUE THREAD

**Issue by raspverry** [ruyo/VRM4U#125]
Hello, im currently using unreal engine 4.26.2.
I found that when i enable VRM4U plugin i cannot launch the project in oculus quest 2, even though build inside unreal engine was successful.
![Capture](https://user-images.githubusercontent.com/71434298/152473109-55480183-82bf-4b63-8f0d-15f9165bff61.PNG)
and it shows this error.
How can i resolve this issue?

**Comment by ruyo** [comment]
Hi.
If you are using BlueprintProject, change it to CPPProject; if you want to use plugins for Mobile in UE4, you need to use CPP project.
If this doesn't solve the problem, please attach the log file.

**Comment by raspverry** [comment]
thank you! 
i create a new CPP Project and it works without issue!
