### ISSUE TITLE
unreal 4.26.2 VRM4U oculus quest tracking issue

### ISSUE THREAD

**Issue by raspverry** [ruyo/VRM4U#126]
Hello, i'm trying VRM4U_tracking preset with Oculus quest 2. I downloaded VRM4U plugin and put it in VRM4U, 
and set unreal engine 4.26.2 project for VR ( also changed the line to bUseQuestTracking = true; in VRM4U.Build.cs).
however, when i start VR preview, i can see VRM character infront of me (really low resolution) and the character is not moving at all.
When i move my head with HMD around, the whole scene is moving like it is literally attached to the camera. 
For example, when i look down, i can see blue ring which shows my position, but the whole scene is turning 90 degree.

Is there any step i missed?

**Comment by ruyo** [comment]
Hi.
In order to use hand tracking, you need to build the project.
Download the plugin source and give it a try.

The resolution in the HMD has been lowered so that the preview screen on the PC monitor side runs smoothly.

**Comment by raspverry** [comment]
yep, i download the source and put it in the folder, but still having the issue.
I'm bit confused with 'build the project'. Is it the button on the tool bar on the project? or is there a way to build in VS code?
What i tried was clicking the button on the tool bar.

**Comment by ruyo** [comment]
If you are using BlueprintProject, try pressing the button shown in the screenshot.

If this step does not work well, please test it with C++Project.
See this link for build details.
https://ruyo-github-io.translate.goog/VRM4U/03_exe/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja

![image](https://user-images.githubusercontent.com/6472835/153200333-4f59c309-d7ab-4ccf-a5ce-1cd573600ea2.png)

**Comment by raspverry** [comment]
oh since it wasn't compiled i had the error. Thank u! it's working fine now
