### ISSUE TITLE
Assign Skeletal Problem report

### ISSUE THREAD

**Issue by SuperHellCat** [ruyo/VRM4U#13]
My Step:
1. Import File_A.vrm and File_B.vrm to UE4.
2. integrate ALSV with File_A_ue4mannequin (Skeletal Mesh) by following your video step by step.
3. Select **File_B_ue4mannequin** (Skeletal Mesh), Assign skeletal to **File_A_ue4mannequin** (Skeletal Mesh).
4. In Anim_BP, Editor mode, Change Vrm Meta Object of VrmSpringBone from **File_A_VrmMeta (VrmMeta)** to **File_B_VrmMeta (VrmMeta)**.
5. UE4 Crash

Assertion failed: Pose.IsValidIndex(BoneIndex) [File:E:\Program Files\EpicGames\UE_4.24\Engine\Source\Runtime\Engine\Public\BonePose.h] [Line: 546]

Things I tryed:
1. Change skeletal mesh and VrmMeta in runtime.
2. Disable VrmSpringBone node first and change skeletal mesh and VrmMeta, once VrmSpringBone node active, game crash.
3. Check and assign new bone index to File_B_VrmMeta 

Still crash when add other VrmMeta data to VrmSpringBone Node.

if you have any idea please help, thanks

**Comment by ruyo** [comment]
Thanks for the report.
Maybe I could fix the crash. I didn't consider skeleton assign with swing bone...
Checking the operation with various data.
The plugin will be updated soon.

**Comment by ruyo** [comment]
I fixed it. Please try the latest plugin.
Thanks!

**Comment by SuperHellCat** [comment]
Thanks! The new plugin is work perfectly. 

Thanks for your great work!
