### ISSUE TITLE
Runtime import engine crash "RenderSection.DuplicatedVerticesBuffer.DupVertData.Num()"

### ISSUE THREAD

**Issue by LethalDumpster** [ruyo/VRM4U#131]
When runtime importing VRM models using the (currently)latest release 20220223, the engine crashes. This occurs with custom made Blender VRM models, and even the sample model AvatarSample_C offered by Vroid Studio 1.4.2.

[ControlRigMannequin.log](https://github.com/ruyo/VRM4U/files/8139169/ControlRigMannequin.log) - UE4.26

Error occurs in both UE4.26 and UE5 Preview 1
Though while that log states the failed assertion is Line: 265 with UE4.26, it reports Line: 250 in UE5 Preview 1.

**Comment by ruyo** [comment]
Thanks for the report.

It will be fixed in the next release.
If you're using the source files, try to get the latest version.

It was fixed by this pullrequest.
https://github.com/ruyo/UnrealEngine_VRM4UPlugin/pull/9

**Comment by LethalDumpster** [comment]
Yep, source works, glad to have it functioning!
