### ISSUE TITLE
Runtime import crash in packaged builds. "RenderSection.DuplicatedVerticesBuffer.DupVertData.Num()"

### ISSUE THREAD

**Issue by KeiraTheCat** [ruyo/VRM4U#136]
**Describe the bug**
Crash occurs when using runtime import through blueprint in a packaged build
`LogWindows: Error: Assertion failed: RenderSection.DuplicatedVerticesBuffer.DupVertData.Num() [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\SkeletalMeshLODRenderData.cpp] [Line: 194] `

**UnrealEngine Version:**
UE5 Preview 1

**Additional context**
this appears to be the same type of crash that was referenced in issue #131 the fix in the linked pull request of this issue (https://github.com/ruyo/UnrealEngine_VRM4UPlugin/pull/9) does allow runtime import to work again in the editor but not in a packaged build. Sorry that I don't have a log to include!

**Comment by ruyo** [comment]
Hi.

Thanks for the report!
This seems to be a problem that only occurs with the UE5Preview pkg.
It works fine in UE4.27.

I will check it out, but it may be a problem specific to the Preview version, so it may not be fixed until the official release.

**Comment by ruyo** [comment]
It will be fixed in the next release.
If you want to test it early, please use the latest version of the plugin source.
Patch support for UE5Preview1.
thanks.
