### ISSUE TITLE
CR_VRoidSimpleMorph保存クラッシュ

### ISSUE THREAD

**Issue by lyuro** [ruyo/VRM4U#138]
UE5 Previewにて
プラグイン内のCR_VRoidSimpleMorphを保存する時もクラッシュします

リリースログで動作しないと記載されましたが、こちはpreview以降にMorphが使えない感じでしょうか？

**Comment by ruyo** [comment]
UE5 Previewにおいては、Selectノードの配列サイズが10を超えると、保存時にクラッシュするようです。
ので、実質的にMorphRigを使えない状態です。

パッチも頂きありがとうございます。
ただこのアセットはUE4.26、4.27と共通で利用しているため、他の回避手段を考え中です。

ログに記載の問題は別で、Morph周りのインポートに問題がありました。この点は最新ソースでは対応済です。
