### ISSUE TITLE
Unwanted blurring edges for animated mesh rendered with BP_PoseCopyToon and other pose-copy functions.

### ISSUE THREAD

**Issue by ShiweiTerryZhou** [ruyo/VRM4U#140]
**Describe the bug**
For meshes rendered with BP_PoseCopyToon or runtime loader. There is a blurring effect on the edge of the copy-pose mesh. Have not able to find any setting that can turn if off so far. I speculate this phenominon to be unintented, hence as a bug. The blurring effect has very significant impact on visuals.

**Screenshots, log**
Here is the video comparing the original pose and copy-pose rendering. The left one is the original, which has very clean edges. The right one is the copy-pose one which has very blurring edges. If you observe eyebrow closely, the right one is to blurry to even show it. 
https://youtu.be/aqqcihHUoLA

**UnrealEngine Version:**
UE4.27

**Additional context**
So far I only observe this issue in BP_PoseCopyToon and runtime loader. This may be a common issue happens to all functionalities that involve copy-pose.

**Comment by ruyo** [comment]
Thank you for your report.

Perhaps the Blur setting in SkeletalMesh is having an effect.
Please toggle this checkbox to confirm.

I will consider changing the default value.
When turned on, there is an issue with characters blurring while paused.
but it seems to be better to prioritize the look of the normal PlayIN appearance.

![image](https://user-images.githubusercontent.com/6472835/157487059-91677ed7-0242-43e4-b6be-a7a99fd7ca82.png)

**Comment by ShiweiTerryZhou** [comment]
Thanks for the reply!

Toggling 'Per Bone Motion Blur' does solve the problem in the case of using BP_PoseCopyToon. However, when I am trying to do it for runtime loader, there seems to be no 'Set Per Bone Motion Blur' available but only get method. Is there any workaround to configure this for the run time loader?

![image](https://user-images.githubusercontent.com/62668258/157539246-6abc26a4-a829-4a65-9c5b-64b7adc63fec.png)

**Comment by ruyo** [comment]
This flag cannot be changed by BP.
Try to set it as the default value for PoseCopy  actor.

I will change the default value in the next release.

**Comment by ShiweiTerryZhou** [comment]
New release resolved this issue. This ticket is good to be closed. Thanks a lot for your help and updated version!
