### ISSUE TITLE
Dissolve effect for vroid model

### ISSUE THREAD

**Issue by HowlC** [ruyo/VRM4U#145]
Hi, actually it is not a bug. 
But this question bothers me for some time.

Since I couldn't utilize opacity mask channel and opacity channel in vrm default material for dissolving effect in UE, 
how can I implement this effect with keeping material features of this plugin?

Any advice is appreciated.

**Comment by ruyo** [comment]
Hi.

See M_VrmMToonBaseOpaque. The DitherAlpha function is available as a CustomEffect. Normally, it is disabled by StaticSwitch.
I think you can add any node with this as a reference.
Thanks

![image](https://user-images.githubusercontent.com/6472835/162278791-fd6cfb70-5d56-4870-83b2-8283f13e4c3d.png)
![image](https://user-images.githubusercontent.com/6472835/162278840-8afbb71e-05a6-4f45-af99-609a2ef26522.png)

**Comment by HowlC** [comment]
Hello.
Thanks for your feedback. 
Actually I noticed dither effect but I need a dissolve effect for death.
Dither effect is more suitable for solving clipping issue when camera is near or inside character occasionally.

Finally I find a solution by extending your base material. 
I share solution here to help other devs who may encounter similar problem:
![FinalResult](https://user-images.githubusercontent.com/77180104/162555965-0b88e52a-ee1d-44df-8618-5047621d61da.png)
![Step1 jpg](https://user-images.githubusercontent.com/77180104/162555966-6cb6e337-061e-4977-8d81-d260e48e011f.png)
![Step2](https://user-images.githubusercontent.com/77180104/162555969-c13fcc2b-dd75-49fb-be28-0ca21e8ca299.Jpg)

Final result:
![FinalResult](https://user-images.githubusercontent.com/77180104/162555974-ca7d243e-1e33-4fd6-bae2-b7853238e39f.png)
