### ISSUE TITLE
I've tried for several hours. Still unable to package

### ISSUE THREAD

**Issue by JS1984222** [ruyo/VRM4U#15]
I'm trying to package from unreal, but get the error:

"ERROR: Could not find definition for module 'VRM4U', (referenced via Eureka_II.uproject -> VRM4U.uplugin)
PackagingResults: Error: Could not find definition for module 'VRM4U', (referenced via Eureka_II.uproject -> VRM4U.uplugin)#"

If I move the files from https://github.com/ruyo/UnrealEngine_VRM4UPlugin manually I get this text: 

"The following modules are missing or built with a different engine version.
VRM4U
VRM4ULoader
VRM4UImporter
VRM4UMisc"

... And if I press yes to rebuilding them I get this message...

"Could not be compiled. Try rebuilding from source manually"

It would make me so happy to be able to package, but I don't understand how to use VRM4U plugin with source code.

...

UPDATE

It works with version 4.23.1, but not 4,24.1

**Comment by ruyo** [comment]
Hi.
Thanks for the report. I could see the same error.

You probably use BlueprintProject. Use C ++ Project to solve it.

There are two ways.

A. Remove VRM4U folder, launch project, add C ++ class and copy VRM4U folder again.  
Any class is ok.

![image](https://user-images.githubusercontent.com/6472835/77557587-457fb500-6efd-11ea-970f-2064c9484c2e.png)

B. Create new C ++ project, copy VRM4U folder and migrate your assets from old project.

I will look for other solutions.
Thanks.

**Comment by JS1984222** [comment]
Thank you ruyo

I'm so happy. Both solutions worked perfectly.

Great job on the plugin.

**Comment by odzta** [comment]
New default CPP Project, migrated from BP project with CPP Class added already but had "Could not find definition for module 'VRM4ULoader'", above work around solved the issue and all working. Then closed new default CPP project and reopened fails again same error 'Could not find definition for module 'VRM4ULoader'  Engine version 4.27

"Creating makefile for DFusedcppEditor (.uproject file is newer)
1>UnrealBuildTool : warning : The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)
1>U:\odzta\UnrealProjects\DFusedcpp\Plugins\VRM4U\VRM4U.uplugin : warning : The 'Developer' module type has been deprecated in 4.24.
1>UnrealBuildTool : error : Could not find definition for module 'VRM4ULoader', (referenced via DFusedcpp.uproject -> VRM4U.uplugin)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(45,5): error MSB3073: The command "U:\EpicGamesGames\UE_4.27\Engine\Build\BatchFiles\Build.bat DFusedcppEditor Win64 Development -Project="U:\odzta\UnrealProjects\DFusedcpp\DFusedcpp.uproject" -WaitMutex -FromMsBuild" exited with code 6.
1>Done building project "DFusedcpp.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped =========="

**Comment by odzta** [comment]
building from source resolved it - thanks. https://ruyo-github-io.translate.goog/VRM4U/03_exe/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=nui

**Comment by xianwew** [comment]
Hi, I tried solution A but it's not working....
