### ISSUE TITLE
"Load VRMFile" blueprint node not importing blendshapes / morph targets properly in a packaged build.

### ISSUE THREAD

**Issue by KeiraTheCat** [ruyo/VRM4U#152]
**Describe the bug**
_Only in a packaged build_, runtime importing through the "Load VRMFile" blueprint node does not allow setting of any morph targets.

**UnrealEngine Version:**
[UE5.0, UE5.0.1]

**Additional context**
I believe this issue only started occurring only after I updated my project to 5.0. I tested this by using the "Load VRMFile" blueprint node to set the asset list in the VrmCharacterBase, re-calling the init function and then setting a morph target. none of the morph targets can be set. The morph target names still appear to load properly just the vertex info is lost, **This all works fine in editor**, just not after packaging a build.

**Comment by ruyo** [comment]
Thank you for your report.

The Morph data does indeed seem to be missing.
I will look into it.
