### ISSUE TITLE
【UE5】コントロールリグにアニメーションをベイクできない

### ISSUE THREAD

**Issue by syakitama** [ruyo/VRM4U#158]
最近のアップデートにより、キャラクターのBodyIKリグを作成することができるようになりました。
アニメーションもこれでつけられるようになり、すごく楽しいです！
ただ、既存のアニメーションおよび新規に作成したアニメーションについて、リグにベイクしようとするとうまくいきません。
かすかに足回りが動いている感じはあるのですが、ぷるぷるっと震える程度です。
シーケンサーにアニメーションを読み込んだ時点でアニメートするはずなのですが、その段階で上記のような感じになります。
導入手順が間違っているのでしょうか？同じ手順でVRMニコニコ立体ちゃんで試しましたが、ダメでした。

**Comment by ruyo** [comment]
報告ありがとうございます。
確かに、新しいリグでは正しくベイクできていないようです… 少々調べてみます。

**Comment by ruyo** [comment]
最新プラグインでベイクに対応しました。
機会あれば使ってみてください。

**Comment by syakitama** [comment]
ご対応いただき、ありがとうございます！
ただ、私のやり方が悪いのかまだうまくいきません。。
手順としては以下のように行っておりますので、見ていただけないでしょうか？
１　現在のプラグインを削除し、最新バージョンを入れる
２　キャラクターデータ（VRM）をUE5上にドラッグアンドドロップ→インポート（設定はデフォルトのまま）
３　Util > Actor > latest にあるCR_VRoidSimpleUE5Bodyを複製し、開く
４　プレビューシーンのメッシュを対象のキャラクターデータのメッシュに差し替える
５　WBP_ControlRigを実行し、BodyRig（UE5）項目のDst Control Rig BPの項目に複製したCR_VRoidSimpleUE5Bodyをセット
６　Reference項目にも対応のアセットをセットし、Generate BodyRigを押す
７　処理が完了したら複製したCR_VRoidSimpleUE5Bodyを開き、コンパイルして保存
８　テストレベルを開き、複製したCR_VRoidSimpleUE5Bodyを投げ込み、シーケンサーを起動させる
９　一番下のアニメーション項目の＋アニメーションを押下し、アニメーションをセットする（この時点でアニメーションしない）
１０　コントロールリグにベイクを押し、複製したCR_VRoidSimpleUE5Bodyを選択（キーが打たれるがアニメーションはしない
）
以上です、よろしくお願いいたします！

**Comment by ruyo** [comment]
この手順では、セットしたアニメーションをTポーズのControlRigで上書きしてしまっています。
 9番の後、シーケンサー上のControlRigのトラックを削除すればアニメーションが動きます。
その状態で ベイクしてみてください。

**Comment by syakitama** [comment]
できました！ありがとうございます！
仕組みを理解していなかったようで申し訳ないです。。
それから、ついでの報告になりますが、右手の親指が特定の座標に居座り、ビヨーンと伸びた状態でベイクされることがあるようです。今回PMX形式モデルで起きた事象なので、サポート外ではあると思いますが、念のため報告しておきます。（モデル固有の問題であるかウェイト設定？の問題とかかもしれません。ニコニコ立体ちゃんでは大丈夫でした）


ありがとうございました！

**Comment by ruyo** [comment]
動いたようでなによりです。
PMXの親指については、設定が足りない箇所がありました。次回リリースで直しておきます。報告ありがとうございます。
