### ISSUE TITLE
Does this work on OSX?

### ISSUE THREAD

**Issue by CreativeCraig** [ruyo/VRM4U#16]
I've been trying for hours to get this to work on my Mac. Is this plugin compatible with Macs or is it Windows only? I haven't seen any information saying either way.

I can't tell for sure, but it seems as if when I unzip the file, it does not create the proper folder hierarchy when unzipping on a mac. I've tried using the default unzip options, the mac version of Winzip, and even unzipping from the terminal, and it still will not unzip properly.

**Comment by ruyo** [comment]
Hi.
This works on Windows only. Sorry for missing the description.

I tried to build it on a Mac and found that it needed a lot of remodeling.
I would like to fix it in the future, but it will take some time..

Thanks.

**Comment by CreativeCraig** [comment]
Thanks for letting me know! No worries :D

I am assuming to circumvent this, I could import the vrm file on a windows machine, and then once they are imported, copy the files from Windows UE4 to a usb drive and then onto a Mac.

**Comment by JS1984222** [comment]
It would be great if your plugin was made for Mac ruyo.

I have tried to copy a VRM4U project from PC to Mac with a flash drive, and not being able to open the file on Mac. 
It would be super if it would be possible to package a game with the VRM4U plugin for both PC and Mac.

**Comment by ARXChrono** [comment]
any updates on this? does it work now?
