### ISSUE TITLE
[UE5] Animation Retargeter and Root Motion

### ISSUE THREAD

**Issue by phuclagger** [ruyo/VRM4U#164]
I'm not sure if this is a bug in UE5 or I did something wrong. When I retarget animations with root motion, the animations themselves come out just fine but the root bone doesn't move, which prevents the root motion from actually working. I used the rig created by VRM4U and WBP_IKRetarget to A-pose the character.

Original animation (with correct root bone movement denoted by the red line in the editor):
![image](https://user-images.githubusercontent.com/7425003/167620488-10b65103-824e-4cb3-af28-9d9999fcef89.png)

Retargeted animation (root bone stays in place):
![image](https://user-images.githubusercontent.com/7425003/167620506-b0f919eb-afb4-466f-a7e0-58561cb8ab8c.png)

**Comment by ruyo** [comment]
Hi.
Please see this slide. Sorry for the Japanese.
You need to change the TransitionMode of Root.

Thanks.

https://www.docswell.com/s/EpicGamesJapan/KQN3EK-UE5-ShareAnimation/45

**Comment by phuclagger** [comment]
Thanks for the quick reply,
I was not aware that you could click on individual chain in the retargeter screen for more settings. That seems to fix it for me now!

**Comment by Lipuchich** [comment]
Hello! This almost worked for me as well, but i still have a little issue left - my retargeted animation does not inherit the Z-axis height of the source. So when i play retargeted animation - it lifts my character up as if the height of the Z axis of the root bone does not change at all.
Could you suggest something to deal with it?
![image](https://github.com/ruyo/VRM4U/assets/127506513/1747fd0a-3a18-4a81-95cd-b8ee5ecd5394)
![image](https://github.com/ruyo/VRM4U/assets/127506513/c7f3a24d-34cb-4b91-a288-4687188a2e48)

On screenshots you can see the source is rolling on the ground correctly and the target is lifted up.
Here is the video

https://github.com/ruyo/VRM4U/assets/127506513/1c3e7c49-4b99-45d7-b9fc-07de8febcafd

**Comment by DragonTein** [comment]
omg you saved my becon
