### ISSUE TITLE
Can't package game when I put my vroid character into the map

### ISSUE THREAD

**Issue by SlySeanDaBomb** [ruyo/VRM4U#174]
**Describe the bug**
I'm getting a lot of errors with the plugin when I try to package my game

**Screenshots, log**
log: https://pastebin.com/73HsYJAN

**UnrealEngine Version:**
UE4.27.2

**Additional context**
I've used this plugin before with no errors but recently I started a new project and got the newer version of vrm4u and now it won't work. I've added the source version to it as explained in this video: https://www.youtube.com/watch?v=IoooTbQbgx4 but that didn't work. I've also deleted the content/actor/util/latest folder too and that didn't help.

**Comment by ruyo** [comment]
Hi.
Only a partial log file is available. Please see here and attach log.
Are you trying a package for android?
As a test, see if you can package it for the PC version.

https://ruyo-github-io.translate.goog/VRM4U/03_exe/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja

**Comment by SlySeanDaBomb** [comment]
Oh sorry about that here is the full log: https://pastebin.com/KqYFDEkj
also yes I can package and open for pc but not android, specifically Oculus Quest 2.

**Comment by SlySeanDaBomb** [comment]
Oh hey I fixed it! Wish I read sooner the part that said choosing which maps to cook would help 😅.
thank you so much!
