### ISSUE TITLE
A-Pose is Not Working Upon Import

### ISSUE THREAD

**Issue by NoticeableScout121** [ruyo/VRM4U#182]
A-pose option is not working. Whether or not I have A-pose ticked upon import, the mesh is always using a T-pose. I'm using UE5.

**Comment by ruyo** [comment]
Hi.
Read this document.
https://ruyo-github-io.translate.goog/VRM4U/03_gray/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja
