### ISSUE TITLE
【UE5】コントロールリグにベイクを使用した際、FK用のコントロールがベイクされない

### ISSUE THREAD

**Issue by AkihiroImada** [ruyo/VRM4U#187]
**Describe the bug**

シーケンサ―から任意のアニメーションに対して「コントロールリグにベイク」を行った際、FK用のコントロール（例えばfoot_r_fk_ctrl）のキーフレームに適切な値が設定されません。（画像1参照）  
コントロールリグは下記ドキュメントに従って
https://ruyo.github.io/VRM4U/06_controlrig/#ue5-body-rig%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B
CR_VRoidSimpleUE5Bodyを複製し、複製UI（WBP_ControlRig）を用いて作成しました。
IKに対するキーフレームは適切に打たれており、IK-FKスイッチの初期値はIK側なのでIKのみ使用する場合は問題化いたしません。

直接の原因についてですが、複製UIを用いて作成されたコントロールリグのBackfowards Solve内の各inversion（例えばleft_arm_inversion）内の処理に不具合があるためかと思います。（画像2参照）
他のFK用コントロールと同様になるよう修正することで挙動が改善することが確認できました。（画像3参照）

従いまして当該ノード生成部分に不具合があるものと思われます。

**Screenshots, log**
画像1 不具合
![image](https://user-images.githubusercontent.com/17783214/179288078-b5743de1-e0ef-4453-9f8c-139fff8a7d50.png)
画像2 原因部分（一部）※ 左腕の例
![image](https://user-images.githubusercontent.com/17783214/179290333-24503657-bf5c-4351-9eb9-439f123af98e.png)
画像3 改善が確認できたノード例（一部）
![image](https://user-images.githubusercontent.com/17783214/179298951-5f1fa699-aed1-401e-990a-891c3498b047.png)

**UnrealEngine Version:**
UE5(5.0.1-19764885+++UE5+Release-5.0)

**VRM4U Build**
VRM4U_5_0_20220711

**Comment by ruyo** [comment]
報告＆改善方法共有ありがとうございます。
指摘の通りの挙動をこちらでも確認できました。RIGのテンプレートに組み込めるか 調査してみます。

**Comment by AkihiroImada** [comment]
ご確認ありがとうございます。よろしくお願いいたします。

**Comment by ruyo** [comment]
最新版にてテンプレートとスクリプトを修正しました。もし機会あればお試しください。
情報ありがとうございました。

**Comment by AkihiroImada** [comment]
**UnrealEngine Version**
UE5(5.0.1-19764885+++UE5+Release-5.0)
**VRM4U Build**
VRM4U_5_0_20220725

上記環境で挙動が修正されたのを確認いたしました。
迅速な対応、誠にありがとうございました。
クローズいたします。
