### ISSUE TITLE
Could you please compile this for 4.25 Preview 7 as well?

### ISSUE THREAD

**Issue by kroaton** [ruyo/VRM4U#19]
Hi,
I love your plugin and would love to use my Vroid characters with the new Niagara improvements. Would it be possible to compile for 4.25? Cheers.

**Comment by ruyo** [comment]
Hi.

Yes. I can use plugin in UE4.25 preview7 with VisualStudio2019.

**Comment by kroaton** [comment]
I've been trying to compile but keep getting an exception trace error. I'm probably doing something wrong. 
Could you please post a binary release when you have some free time?
Thank you for your hard work!

**Comment by kroaton** [comment]
Thank you!
