### ISSUE TITLE
Wrist Twist

### ISSUE THREAD

**Issue by YoyoDPanda** [ruyo/VRM4U#190]
Hi Ruyo / anyone,

I have a wrist twist issue - anytime the hand twists the wrist mesh also twists severely (screenshot below).

I tried importing my character to Blender, added bones manually and even tried adding a new rig with Rigify and tried weight painting and even tried Mixamo's automatic rigging but nothing works. I also messed around with the IK stuff in UE5 but I didn't really understand what I was doing there because I'm quite new to Unreal Engine^^

If anyone has a tip/advice or a guide I can follow I'd appreciate it!

![TwistingHand](https://user-images.githubusercontent.com/109741925/181097798-eeaf0d65-5a5f-461a-b882-c9191b6de9fd.png)

And thank you Ruyo for this plugin.

**Comment by ruyo** [comment]
Hi.
Please refer to this link.
Fundamentally, the model needs to be modified.
VRM4U has a simple torsion reduction feature.
https://ruyo-github-io.translate.goog/VRM4U/07_controlrig_morph/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja

Thanks.
