### ISSUE TITLE
textures missing

### ISSUE THREAD

**Issue by Monkeylolz** [ruyo/VRM4U#2]
hello ruyo,
I'm using ue4.22.3.
its all good in the editor but if I launch the game or package the game , 
textures will disappear.
I don't know how to solve it. Please help.

here's the video: https://www.youtube.com/watch?v=9-DdeCwzv-I
(I only record the launching part but it will be the same result if I package it.)

**Comment by ruyo** [comment]
Please try adding "Plugins" to .uproject file.
{
  "FileVersion": 3,
  "EngineAssociation": "4.22",
  "Category": "",
  "Description": "",
  "Plugins": [
    {
      "Name": "VRM4U",
      "Enabled": true
    }
  ]
}

If you still get an other error, 
try using a plugin with source in the UnrealEngine_VRM4UPlugin repository.

Thanks.

**Comment by kane977** [comment]
i cant find this page
"UnrealEngine_VRM4UPlugin"

**Comment by Monkeylolz** [comment]
thanks for reply.
I have added "Plugins" in .uproject file and put source file in but I still got some errors.
If I launch the game,it says " Unable to load plugin 'VRM4U' ".
If I package the game,it says " Cook failed " and says there are 3 files got error.
So I deleted those files which called "MToonActorLeap" , "MToonActorLipSync" and "ABP_VRoidLeap".
After I deleted them, packaging succeeded but I cannot execute the game.

here's the video : https://www.youtube.com/watch?v=JaV76XNmuI4

**Comment by ruyo** [comment]
Thanks for trying.
copy
MyProject\Plugins\VRM4U\ThirdParty\assimp\bin\x64\assimp-vc140-mt.dll
to
WindowsNoEditor\MyProject\Binaries\Win64\

I will try to fix it..

**Comment by ruyo** [comment]
> i cant find this page
> "UnrealEngine_VRM4UPlugin"

show this page.
https://www.unrealengine.com/en-US/blog/updated-authentication-process-for-connecting-epic-github-accounts?sessionInvalidated=true

**Comment by Monkeylolz** [comment]
thanks again for replying.
I have copied "assimp-vc140-mt.dll" to "WindowsNoEditor\MyProject\Binaries\Win64\",
but the game still cannot be executed.

here's the video : https://youtu.be/k78sgvHZvvs

I will wait for fixing.
Thank you!

**Comment by ruyo** [comment]
Hi.
I fixed it.
https://github.com/ruyo/UnrealEngine_VRM4UPlugin/commit/fab437380f28b0802cd792984f223cc3b3a83166

If you are still in trouble,
please try using the latest version.
Thanks.

**Comment by Monkeylolz** [comment]
Perfect!
I can launch and package the game without textures missing now.

thanks for the help.
really appreciate it!

**Comment by ruyo** [comment]
Welcome!

**Comment by chriscast** [comment]
Good day, Ruyo, 

I have the same issue as MonkeyLolz,

no textures on Packaged Project (but works beautifully in editor play)

Ive downloaded the Latest vrm4u version(master release?)
 (but im still using unreal 4.22, is that an issue?) should i upgrade to unreal 4.23?

**Comment by ruyo** [comment]
Hi chriscast.

I can make package using both 4.22 and 4.23.
Could you use plugin from https://github.com/ruyo/UnrealEngine_VRM4UPlugin ?
(try https://www.unrealengine.com/en-US/blog/updated-authentication-process-for-connecting-epic-github-accounts)

thanks!

**Comment by chriscast** [comment]
thank you for reply sir,

here is what i did step by step.

Downloaded(zip)  from Vrm4u_master
![vroid 1](https://user-images.githubusercontent.com/8019845/66710516-ccf0c600-edac-11e9-9443-6bd107c01e63.PNG)

Extracted the Plugins folder to the project folder(my test project)
![vroid 2](https://user-images.githubusercontent.com/8019845/66710519-df6aff80-edac-11e9-80a3-e42b3cac3f56.PNG)

Ran the project, and UE "built" the plugin?
![vroid 3](https://user-images.githubusercontent.com/8019845/66710523-f7428380-edac-11e9-9c33-516f9d7e1b7e.PNG)
![vroid 4](https://user-images.githubusercontent.com/8019845/66710525-01fd1880-edad-11e9-9afe-e745f7c927a4.PNG)

Deleted some stuff to allow Cook
![vroid 5](https://user-images.githubusercontent.com/8019845/66710528-14775200-edad-11e9-95a8-0fba4dc272f9.png)

Built package (windows 64 bit) success
![vroid 6](https://user-images.githubusercontent.com/8019845/66710533-278a2200-edad-11e9-8384-f4b379251ef0.png)

Test with EXE file
![vroid 8](https://user-images.githubusercontent.com/8019845/66710536-34a71100-edad-11e9-9b79-fdfdfb1090fc.PNG)

No textures, with Exe file but textures okay inside Play-In-Editor

Thank you for responding.

**Comment by ruyo** [comment]
Thank you for the details explanation!

I fixed it.
Please try latest UnrealEngine_VRM4UPlugin. 

It is correct procedure. But not works in blueprint project as you say.
I make VRM4U as installed plugin and remove BPs for test.

**Comment by chriscast** [comment]
Wow Thank you! 

It now packages correctly and perfectly!
