### ISSUE TITLE
Cannot install the plugin and cannot open example project

### ISSUE THREAD

**Issue by Zenahr** [ruyo/VRM4U#20]
こんにちは Ruyo,
Thanks for the plugin and your hard work!

I downloaded the plugin release from here:
![image](https://user-images.githubusercontent.com/47085752/81230399-b1bc0100-8ff1-11ea-9f62-9522da2bbb8b.png)

The log message I get when trying to open the example project is:

'UEBuildBinaryConfiguration' could not be found (are you missing a using directive or an assembly reference?)

Any help would be very much appreciated!
ありがとうございました！

COMPLETE LOG MESSAGE:
--------------------------------------------------------------
Running D:/Epic Games/UE_4.24/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="D:/Epic Games/UE_4.24/Unreal-Engine-4-Plugins-master/Plugins Example Project/Plugins.uproject" -game -rocket -progress -log="D:\Epic Games\UE_4.24\Unreal-Engine-4-Plugins-master\Plugins Example Project/Saved/Logs/UnrealVersionSelector-2020.05.06-23.29.17.log"
Discovering modules, targets and source code for project...
While compiling D:\Epic Games\UE_4.24\Unreal-Engine-4-Plugins-master\Plugins Example Project\Intermediate\Build\BuildRules\PluginsModuleRules.dll:
d:\Epic Games\UE_4.24\Unreal-Engine-4-Plugins-master\Plugins Example Project\Source\Plugins.Target.cs(19,12) : error CS0246: The type or namespace name 'UEBuildBinaryConfiguration' could not be found (are you missing a using directive or an assembly reference?)
d:\Epic Games\UE_4.24\Unreal-Engine-4-Plugins-master\Plugins Example Project\Source\PluginsEditor.Target.cs(19,12) : error CS0246: The type or namespace name 'UEBuildBinaryConfiguration' could not be found (are you missing a using directive or an assembly reference?)
ERROR: Unable to compile source files.

**Comment by ruyo** [comment]
Hi.

Please use latest source from vrm4u_master branch.
There is a problem in this operation because it does not use tags. However, this plugin cannot guarantee stability during development, so it does not make much sense to tag it...

Thanks.

**Comment by gingerbeardbaker** [comment]
I got the latest source from vrm4u_master branch, but get an error. Do I need to install differently than the development version via the Plugin folder? Am using UE 4.24.3 through Epic Launcher.

**Comment by Zenahr** [comment]
> Hi.
> 
> Please use latest source from vrm4u_master branch.
> There is a problem in this operation because it does not use tags. However, this plugin cannot guarantee stability during development, so it does not make much sense to tag it...
> 
> Thanks.

Well you can still tag releases with for example 0.12.0-alpha and check the "this is a pre-release" checkbox when creating your releases if that's what you were talking about. Just a suggestion, but I do get your perspective.
