### ISSUE TITLE
Anyway to set semi transparency of material in Unreal

### ISSUE THREAD

**Issue by pasunna** [ruyo/VRM4U#210]
The vroid default material don't have semi transparency for cloth and skin except sock and underwear 
any way to change that in unreal material to accept semi transparency effect?
When I set overide material to translucent
the outcome look very weird
are there a propery way to do it?

**Comment by pasunna** [comment]
![image](https://user-images.githubusercontent.com/3685802/195633397-6fda0160-a6cd-4dd2-b038-aec67e25cbf0.png)

**Comment by ruyo** [comment]
Hi.
Please use DitherAlpha.
This will also switch existing alpha values to dither representation.
![image](https://user-images.githubusercontent.com/6472835/195974060-36aaa92c-df61-443a-87c4-a0aa252364a8.png)

Thanks.

**Comment by pasunna** [comment]
thanks it working
still want more clearer transparent but atleast itwork
