### ISSUE TITLE
Can't Package in UE5.0.3

### ISSUE THREAD

**Issue by VenariArtist** [ruyo/VRM4U#227]
**Describe the bug**
I'm unable to package my game in UE5.0.3. I enabled the code from https://github.com/ruyo/VRM4U/releases for UE5.0.3 into the project folder instead of the engine folder. It worked fine. I then after closing the project overwrote that code with the source from https://github.com/ruyo/UnrealEngine_VRM4UPlugin. Then I opened the project disabled the plugin, restarted, then enabled it again, and restarted. The plugin worked fine except when I try to package it. I've narrowed it down it IS the plugin causing my game not to package when I did these steps with a brand new project that packaged fine right before I enabled the plugin. There is no models or anything else in the project for the Third person character project. It gives in red a "UATHelper: Packaging (Windows): ERROR: Cook failed." and "PackagingResults: Error: Cook failed." Building the project in Visual Studio 2019 didn't fix this issue either. Even just existing inside the Project file causes it to get the "PackagingResults: Error: Cook failed.". I had it in the project file in a new folder called Plugins and I also tried deleting the "latest" folder to try to fix this. The plugin even after removed permanently makes the project unable to package.

**Screenshots, log**
In Yellow:
UATHelper: Packaging (Windows): WARNING: Warning: Plugin 'VRM4U' does not list plugin 'IKRig' as a dependency, but module 'VRM4U' depends on 'IKRig'.
UATHelper: Packaging (Windows): WARNING: Warning: Plugin 'VRM4U' does not list plugin 'IKRig' as a dependency, but module 'VRM4ULoader' depends on 'IKRig'.
PackagingResults: Warning: Warning: Plugin 'VRM4U' does not list plugin 'IKRig' as a dependency, but module 'VRM4U' depends on 'IKRig'.
PackagingResults: Warning: Warning: Plugin 'VRM4U' does not list plugin 'IKRig' as a dependency, but module 'VRM4ULoader' depends on 'IKRig'.

In Red:
UATHelper: Packaging (Windows): ERROR: Cook failed.
PackagingResults: Error: Cook failed.

![Error 1](https://user-images.githubusercontent.com/73431036/205478705-2c661634-62ab-47af-8f5c-0b35e6180f2c.png)

![Error 2](https://user-images.githubusercontent.com/73431036/205478708-449c31f3-e61d-4351-9bbd-2acbe4cc68ba.png)

**UnrealEngine Version:**
UE5.0.3

**Comment by ruyo** [comment]
Hi.
To create a package using VRM4U, you will need to change the project to a C++ project. Please add a new C++ file and then try it.
Please remember to backup your project just in case.
Thanks.

**Comment by VenariArtist** [comment]
Ruyo I did do that. That's why I mention "Building the project in Visual Studio 2019 didn't fix this issue either." This didn't fix it. Your plugin has a glitch.

**Comment by VenariArtist** [comment]
> Hi. To create a package using VRM4U, you will need to change the project to a C++ project. Please add a new C++ file and then try it. Please remember to backup your project just in case. Thanks.
