### ISSUE TITLE
BP_dropActorのCast to VrmAnimInstanceCopyについて

### ISSUE THREAD

**Issue by monpoke8888** [ruyo/VRM4U#23]
こんばんは、いつもVRM4Uで遊ばせていただいております。
現在ランタイムロードがゲームにつかえないかをためしているのですが。
BP_dropActorのCast to VrmAnimInstanceCopyがcast FailedしてBP_dropActorにプレイヤーの
アニメーションが反映されません、何か設定など必要でしょうか。

なお、VRMファイル自体はTポーズでロードされています。

利用環境’UE4.22 VRM4U 20200520リリース
　　　　UE4.24、UE4.2５でも同じ現象を確認しております。

**Comment by ruyo** [comment]
ありがとうございます。

ひとまず以下のようにノードを追加すれば、アニメーションが動作すると思います。
![image](https://user-images.githubusercontent.com/6472835/82694015-7da53900-9c9d-11ea-98da-1a9712672736.png)

手元ではあまり動作確認していませんでした。。
次回リリースにてサンプルを修正します。

なお現状ではラインタイムロードにおけるインポートオプション変更は、ソースコードの書き換えが必要です。のでご注意ください。

**Comment by monpoke8888** [comment]
教えていただいた内容で解決できました、ありがとうございました！
