### ISSUE TITLE
Package(Sttings)

### ISSUE THREAD

**Issue by Adriano94** [ruyo/VRM4U#235]
Hello, I have this problem when I package:

**_UATHelper: Packaging (Windows (64-bit)):   ERROR: Missing precompiled manifest for 'Settings'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in Settings.build.cs to override.
PackagingResults: Error: Missing precompiled manifest for 'Settings'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in Settings.build.cs to override.
UATHelper: Packaging (Windows (64-bit)): Took 2,16209s to run UnrealBuildTool.exe, ExitCode=6. )_** 

I already tested it and when I deactivate the VRM4U plugin it doesn't give this error, but I need VRM4U for my project. would you know how to help me solve the problem?

[UBT-Hikare_no_Mae-Win64-Shipping.txt](https://github.com/ruyo/VRM4U/files/10297283/UBT-Hikare_no_Mae-Win64-Shipping.txt)

**Comment by WhyAreLess** [comment]
Did you get the VRM4U from here aswell? https://github.com/ruyo/UnrealEngine_VRM4UPlugin

Put that in the Plugins folder aswell and overwrite the VRM4U folder

**Comment by Adriano94** [comment]
Yes, I had already taken this one and it keeps giving this error

**Comment by Adriano94** [comment]
> Você conseguiu o VRM4U daqui também? https://github.com/ruyo/UnrealEngine_VRM4UPlugin (clique no botão de código verde e baixe o ZIP)
> 
> Coloque isso na pasta Plugins também e sobrescreva a pasta VRM4U

Yes, I had already taken this one and it keeps giving this error

**Comment by Adriano94** [comment]
From what I've been testing this problem only happens in package shipping, in other configurations it worked normally

**Comment by ruyo** [comment]
Hi.
Sorry, fixed in the latest version of the source.
Module reference has been reviewed.

**Comment by Adriano94** [comment]
> Hi. Sorry, fixed in the latest version of the source. Module reference has been reviewed.

worked for me, thanks
