### ISSUE TITLE
Error to import in UE 5

### ISSUE THREAD

**Issue by Cleideson** [ruyo/VRM4U#25]
Hello again, i have a issue to use in UE5, i change the Developer mode to UncookedOnly, but the issues continue.
![error](https://user-images.githubusercontent.com/13318338/82708647-22e7ef00-9c55-11ea-96ae-2871231d91a2.PNG)

**Comment by ruyo** [comment]
Hi.

What kind of operation is this error caused by?
It does not appear to be an import error.

If you want to compile or package the plugin itself in any way, please use the source at https://github.com/ruyo/UnrealEngine_VRM4UPlugin.

**Comment by Cleideson** [comment]
This link saying that the page does not exist, I used this version VRM4U_4_25_20200520.zip inside the folder of my project

**Comment by ruyo** [comment]
Please Connecting Epic, GitHub Accounts.

https://www.unrealengine.com/en-US/blog/updated-authentication-process-for-connecting-epic-github-accounts

**Comment by Cleideson** [comment]
I connected my github account to epic and compiled the code and it worked

**Comment by Cleideson** [comment]
I connected my github account to epic and compiled the code and it worked
