### ISSUE TITLE
Packaging Error - Could not find definition for module 'VRM4U'

### ISSUE THREAD

**Issue by Animeke** [ruyo/VRM4U#265]
**Describe the bug**
The 5.2 plugin is causing an error when packaging my project.

**UnrealEngine Version:**
UE5.2 (Installed through launcher)

**Additional context**
UATHelper: Packaging (Windows): Could not find definition for module 'VRM4U', (referenced via Project.uproject -> VRM4U.uplugin)
UATHelper: Packaging (Windows): Took 1.387428s to run dotnet.exe, ExitCode=6
UATHelper: Packaging (Windows): UnrealBuildTool failed. See log for more details. (C:\Users\---\AppData\Roaming\Unreal Engine\AutomationTool\Logs\S+UE_5.2\UBT-Project-Win64-Development_2.txt)
UATHelper: Packaging (Windows): AutomationTool executed for 0h 0m 6s
UATHelper: Packaging (Windows): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by 720bit** [comment]
Also got this issue and did all the same steps to get it to package in 5.1.1 and there it works

**Comment by Animeke** [comment]
> Also got this issue and did all the same steps to get it to package in 5.1.1 and there it works

I would revert to 5.1 but my project has 5.2 dependent features unfortunately. I'm really hoping there's a way to fix this or I might have to disable the plugin for now and reformat my project.

**Comment by 720bit** [comment]
Yeah I went back to 5.1 I dont need 5.2 for this project can wait

**Comment by ruyo** [comment]
Hi.
Please refer here to obtain the source code and set it up.
https://ruyo-github-io.translate.goog/VRM4U/03_exe/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja

**Comment by Animeke** [comment]
> Hi. Please refer here to obtain the source code and set it up. https://ruyo-github-io.translate.goog/VRM4U/03_exe/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja

Thank you ruyo, this worked!
