### ISSUE TITLE
IK Rig broken on packaging project

### ISSUE THREAD

**Issue by 720bit** [ruyo/VRM4U#266]
**Describe the bug**
In editor the character is perfectly retargeted with IK
when the project is built the IK is gone and the retarget causes bone snapping

**Screenshots, log**
UATHelper: Packaging (Windows): Log file: C:\Users\MichaelRyzen9\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Users+MichaelRyzen9+Documents+Games+UE_5.1\UBT-OpenWorld01-Win64-Shipping.txt
UATHelper: Packaging (Windows): Warning: Plugin 'VRM4U' does not list plugin 'IKRig' as a dependency, but module 'VRM4U' depends on 'IKRig'.
PackagingResults: Warning: Plugin 'VRM4U' does not list plugin 'IKRig' as a dependency, but module 'VRM4U' depends on 'IKRig'.
UATHelper: Packaging (Windows): Warning: Plugin 'VRM4U' does not list plugin 'IKRig' as a dependency, but module 'VRM4ULoader' depends on 'IKRig'.
UATHelper: Packaging (Windows): Writing manifest to C:\Users\MichaelRyzen9\Documents\GitHub\OpenWorld01\Intermediate\Build\Manifest.xml
PackagingResults: Warning: Plugin 'VRM4U' does not list plugin 'IKRig' as a dependency, but module 'VRM4ULoader' depends on 'IKRig'.
UATHelper: Packaging (Windows): Target is up to date

![OpenWorld01 - Unreal Editor 4_28_2023 9_10_30 PM](https://user-images.githubusercontent.com/49247495/235278942-2a6cf14f-1033-48f3-9532-e8e16b932543.png)

![Movies   TV 4_28_2023 9_13_33 PM](https://user-images.githubusercontent.com/49247495/235279049-6cdf2b92-d72b-400a-842b-daf358a6ddf7.png)

UE 5.1.1

**Additional context**
All steps can be replicated,

**Comment by 720bit** [comment]
Figured out how to fix this, remove the full body Ik solver in the IK Rig of your character because if you are doing as I am and using the retarget pose from mesh the retarget mesh already has an IK Rig to use.

**Comment by 720bit** [comment]
as for the message error this fixed it 

https://github.com/ruyo/VRM4U/issues/184#issuecomment-1243253550

**Comment by Animeke** [comment]
Just discovered this issue in my own project, thanks for figuring it out!
