### ISSUE TITLE
How to import pmx files of genshin impact to ue5?

### ISSUE THREAD

**Issue by zaichenhu** [ruyo/VRM4U#273]

**Comment by ruyo** [comment]
Hi.
Please see this page
https://ruyo-github-io.translate.goog/VRM4U/04_import/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja

**Comment by zaichenhu** [comment]
thanks, but moust pmx files don't contain physics assets like vrm does, if there is any process to create physics asset automatically?

**Comment by zaichenhu** [comment]
ok, thank you!
