### ISSUE TITLE
Random crashed when VRM assets are viewed in browser

### ISSUE THREAD

**Issue by ToffelsKater** [ruyo/VRM4U#284]
**Describe the bug**
Whenever a asset is viewed in the content drawer that has VRM references the engine crashes
It worked before i added VRM spring bone component in anim BP
It can crash if adding virtual bones too

**Screenshots, log**
<img width="1409" alt="image" src="https://github.com/ruyo/VRM4U/assets/20298637/663d8d5c-e02d-4223-aaf6-220c8e7a6cb9">

**UnrealEngine Version:**
5.2

**Additional context**
using VRM4U_5_2_20230530
[AdvancedJigsawInventorysy.log](https://github.com/ruyo/VRM4U/files/11682798/AdvancedJigsawInventorysy.log)

**Comment by ruyo** [comment]
Hi.
It looks like it works fine as far as I have tested it.
Try importing the data into a different folder to create the files.
There may be some broken asset links.

![image](https://github.com/ruyo/VRM4U/assets/6472835/e2dc53be-bcbe-4e45-9b05-3eb6534deb84)

**Comment by ToffelsKater** [comment]
Alright I'll check again, but thanks for looking into it
