### ISSUE TITLE
【UE5.2.0】VRMSpringBoneを使用するとアニメーションがTポーズのままになる

### ISSUE THREAD

**Issue by atarime1111** [ruyo/VRM4U#288]
**Describe the bug**
UE5.0.1 plugin version 20220809 or 28 から UE5.2.0 plugin version 20230530 にアップデートしたところ、アニメーションBluePrint内でVRMSpringBoneを使用するとアニメーションが適用されない(Tポーズのまま)という事象が発生しました。
プラグインの不具合でしょうか
UE5.0.1 plugin version 20220828の環境に戻して再度試行すると問題は見られませんでした

**UnrealEngine Version:**
UE5.2.0

**Additional context**
Plugin Version 20230530

**Comment by ruyo** [comment]
報告ありがとうございます。
UE5.2にて、SprintBoneノードの初期化が不足しており、アニメーションが流れなくなっていました。
最新のプラグインで修正しています。
