### ISSUE TITLE
Assertion failed: IsRotationNormalized() 

### ISSUE THREAD

**Issue by inatos** [ruyo/VRM4U#289]
UE crashes when trying to run game in editor.

**Screenshots, log**
![image](https://github.com/ruyo/VRM4U/assets/32039018/08bf9efb-d3c4-4122-8ecf-08c344cb035f)

`VRMSpringBone.VM_VrmMeta` node fails with this:
![image](https://github.com/ruyo/VRM4U/assets/32039018/a80c281b-139c-4a1f-b1da-e85f5bc585ae)

- Using UE5.1.1

**Comment by inatos** [comment]
Found some more info in the crash log:
```

**Comment by inatos** [comment]
If it helps, I'm using the Lyra Animation system from the Lyra FPS project. Does VRM4U work with layered animations?

**Comment by inatos** [comment]
Fixed by updating to newest VRM4U version and reimported SK.

**Comment by frankiezafe** [comment]
The issue, in my case, was provoked by using the empty constructor of `FQuat`.
Fix is detailed here: https://forums.unrealengine.com/t/unreal-engine-assertion-failed-isrotationnormalized-error/1209437/2
