### ISSUE TITLE
import .vrm crash

### ISSUE THREAD

**Issue by rafadsm** [ruyo/VRM4U#3]
my engine crash on drop .vrm file in editor
![import](https://user-images.githubusercontent.com/25557084/65810649-453b7280-e183-11e9-94b5-7468fd04eecf.png)

created in vroid studio
[test-character.zip](https://github.com/ruyo/VRM4U/files/3665043/test-character.zip)

**Comment by ruyo** [comment]
Hi.
I can import your vrm file with UE4.20 and UE4.23.
Can you play VRM4U sample maps? Please use latest plugin and check your UE4 version.

Thanks.

![image](https://user-images.githubusercontent.com/6472835/65817411-7bd7c280-e241-11e9-83de-ab9764947879.png)

**Comment by FinnProjects** [comment]
Yes, I can use all the content of the plugin, I am using the latest version of the plugin and the engine, I saw in a video that someone made about the plugin, in the comment there were also some people with the same problem

**Comment by ruyo** [comment]
Sorry for the bug.
Please attach the latest files from Logs and Crashes in ProjectName/Saved.

If you can try plugin from source repository, please tell me a error message.

**Comment by FinnProjects** [comment]
[UE4Log.zip](https://github.com/ruyo/VRM4U/files/3671732/UE4Log.zip)

I recompiled the plugin and succeeded

**Comment by ruyo** [comment]
Thank you!
There is no dll file. Please extract VRM4U_4_23.zip again and check the file.

Game_2.log
[2019.09.27-20.53.20:857][  0]LogWindows: Failed to load 'C:/Users/----/Documents/Unreal Projects/Game/Plugins/VRM4U/ThirdParty/assimp/bin/x64/assimp-vc140-mt.dll' (GetLastError=126)
[2019.09.27-20.53.20:857][  0]LogWindows: File 'C:/Users/----/Documents/Unreal Projects/Game/Plugins/VRM4U/ThirdParty/assimp/bin/x64/assimp-vc140-mt.dll' does not exist

**Comment by AgentOttsel** [comment]
Hello, ruyo! Thank you for creating this plugin. It is wonderful!

I use Unreal Engine 4.22, and with the 2019/07/24 release of your plugin, I could import characters without any errors. After upgrading to the newest version, I was getting the same error described by Finn.

I checked my logs and I also had the error "assimp-vc140-mt.dll does not exit". The thing is, my plugin is installed in the UE4_4.22 folder ("C:\Program Files\Epic Games\UE_4.22\Engine\Plugins\VRM4U"), but the plugin is searching for the assimp DLL in my project's files (C:/Users/AgentOttsel/OneDrive/Documents/Unreal Projects/GrappleBash 4.22/Plugins/VRM4U/ThirdParty/assimp/bin/x64/assimp-vc140-mt.dll). Once I copied assimp-vc140-mt.dll to the "Plugins/VRM4U/ThirdParty/assimp/bin/x64/" path inside my project, importing files with VRM4U started working again. \( ﾟヮﾟ)/

Unless that DLL needs to be part of every project for a reason, I think the plug-in should be looking for assimp-vc140-mt.dll in the same folder that it is installed.

Hopefully this will help you and other people who are having the same issue! ありがとうございます！:)

**Comment by ruyo** [comment]
Thank you so much!

Sorry for the inconvenience.
I fixed it.  You can use the latest VRM4U as both engine plugin and project plugin.

**Comment by AgentOttsel** [comment]
Thank you for fixing this so quickly! It works perfectly for me now. :)

**Comment by pingover123** [comment]
Hello, I love your plugin it's so easy for import model from Vroid
but,When I package the project It's failed to packaging...
![image](https://user-images.githubusercontent.com/48848163/91508051-a2462800-e900-11ea-9e8b-99ea7dc54ea7.png)
How i can fix it to build packaging?
![Capture](https://user-images.githubusercontent.com/48848163/91507928-50050700-e900-11ea-8787-d43b829e6912.JPG)
