### ISSUE TITLE
Package problem

### ISSUE THREAD

**Issue by NowListen** [ruyo/VRM4U#30]
Hello, Luyo,
I used ue4.25.0.
Everything is fine in the game, but if I launch the game pack,The skeleton mesh seems to be 
By checking the log prompt: attempting to load a bulkdata object that cannot be loaded from disk, whether it is due to texture writing and reading problems

1:Screenshot of import at Package：
![VRM_InPackage](https://user-images.githubusercontent.com/36050211/83386159-1e71c200-a41d-11ea-8950-0b7cec2e276d.png)

2：Screenshot of import at Game：
[
![VRM_InGame](https://user-images.githubusercontent.com/36050211/83385638-2da44000-a41c-11ea-8d70-f197ee2f3aa7.png)
](url)

**Comment by ruyo** [comment]
Hi.

The lack of implementation in 4.25 has been fixed.
Try using the latest version.

Thanks for the report!

**Comment by NowListen** [comment]
Hello, when I want to use multiple sets of VRM to use the same animation blueprint, it can be displayed normally in the Game, but after packaging, it will not work well at runtime, and there will be deformation.
I :At Game
1：Simple animation blueprint tested
![微信截图_20200602112047](https://user-images.githubusercontent.com/36050211/83476500-837ff300-a4c3-11ea-97a5-afd6f90d05a3.png)

2：Screenshot before switching VRM in the game：
![微信截图_20200602111529](https://user-images.githubusercontent.com/36050211/83476405-3ef45780-a4c3-11ea-86f5-7aef23f84c40.png)

3：Screenshot After switching VRM in the game：
![微信截图_20200602111551](https://user-images.githubusercontent.com/36050211/83476691-f12c1f00-a4c3-11ea-956e-28c222e9cc3a.png)

I :At Package Game
1：Screenshot before switching VRM in the Package Game：
![微信截图_20200602111849](https://user-images.githubusercontent.com/36050211/83476733-0acd6680-a4c4-11ea-8807-1b96fd0ed85e.png)

2：Screenshot After switching VRM in the Package Game：
![微信截图_20200602111925](https://user-images.githubusercontent.com/36050211/83476781-2f294300-a4c4-11ea-9810-cfc7ea1cab2a.png)

**Comment by NowListen** [comment]
@ruyo Hello, the problem above is a bug that hasn't been fixed

**Comment by ruyo** [comment]
All right. I'm sorry for the lack of confirmation.
I' ve got a special implementation of runtime loading, so I would like to take some time to fix it...

**Comment by NowListen** [comment]
Thank you for your reply.

**Comment by ruyo** [comment]
I fixed the model weights not working properly.
Please try the latest version.

Thanks.

**Comment by NowListen** [comment]
Thank you for the repair.
