### ISSUE TITLE
[UE5.2]Crash happened after importing .bvh

### ISSUE THREAD

**Issue by Owlcean** [ruyo/VRM4U#300]
**Describe the bug**
I cannot import any bvh file,which leads to a crash

**Screenshots, log**
Assertion failed: MovieScene [File:D:\build\++UE5\Sync\Engine\Plugins\Animation\AnimationData\Source\AnimationData\Private\AnimSequencerDataModel.cpp] [Line: 931] No Movie Scene found for SequencerDataModel

UnrealEditor_AnimationData!UAnimationSequencerDataModel::ValidateSequencerData() [D:\build\++UE5\Sync\Engine\Plugins\Animation\AnimationData\Source\AnimationData\Private\AnimSequencerDataModel.cpp:931]
UnrealEditor_AnimationData!UAnimationSequencerDataModel::GetFrameRate() [D:\build\++UE5\Sync\Engine\Plugins\Animation\AnimationData\Source\AnimationData\Private\AnimSequencerDataModel.cpp:275]
UnrealEditor_Engine!IAnimationDataController::ConvertSecondsToFrameNumber() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Classes\Animation\AnimData\IAnimationDataController.h:691]
UnrealEditor_AnimationData!UAnimSequencerController::SetPlayLength() [D:\build\++UE5\Sync\Engine\Plugins\Animation\AnimationData\Source\AnimationData\Private\AnimSequencerController.cpp:213]
UnrealEditor_VRM4ULoader
UnrealEditor_VRM4ULoader
UnrealEditor_VRM4ULoader
UnrealEditor_VRM4UImporter
UnrealEditor_UnrealEd!UFactory::FactoryCreateFile() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\Factories\Factory.cpp:116]
UnrealEditor_UnrealEd!UFactory::ImportObject() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\Factories\Factory.cpp:208]
UnrealEditor_AssetTools!UAssetToolsImpl::ImportAssetsInternal() [D:\build\++UE5\Sync\Engine\Source\Developer\AssetTools\Private\AssetTools.cpp:3624]
UnrealEditor_AssetTools!UAssetToolsImpl::ImportAssets() [D:\build\++UE5\Sync\Engine\Source\Developer\AssetTools\Private\AssetTools.cpp:2542]
UnrealEditor_UnrealEd!FImportFilesByPath::Run() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\Subsystems\ImportSubsystem.cpp:97]
UnrealEditor_UnrealEd!UImportSubsystem::HandleNextTick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\Subsystems\ImportSubsystem.cpp:171]
UnrealEditor_UnrealEd!TBaseUObjectMethodDelegateInstance<0,UImportSubsystem,void __cdecl(void),FDefaultDelegateUserPolicy>::Execute() [D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:535]
UnrealEditor_Engine!FTimerUnifiedDelegate::Execute() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Public\TimerManager.h:48]
UnrealEditor_Engine!FTimerManager::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\TimerManager.cpp:933]
UnrealEditor_UnrealEd!UEditorEngine::Tick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\EditorEngine.cpp:1529]
UnrealEditor_UnrealEd!UUnrealEdEngine::Tick() [D:\build\++UE5\Sync\Engine\Source\Editor\UnrealEd\Private\UnrealEdEngine.cpp:519]
UnrealEditor!FEngineLoop::Tick() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5812]
UnrealEditor!GuardedMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Launch.cpp:188]
UnrealEditor!GuardedMainWrapper() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:107]
UnrealEditor!LaunchWindowsStartup() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:244]
UnrealEditor!WinMain() [D:\build\++UE5\Sync\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:284]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**UnrealEngine Version:**
5.2.1
[VRM4U_5_2_20230716.zip](https://github.com/ruyo/VRM4U/releases/download/20230716/VRM4U_5_2_20230716.zip)

**Additional context**
I also tried UE5.1 and plugin verson [VRM4U_5_1_20230716.zip](https://github.com/ruyo/VRM4U/releases/download/20230716/VRM4U_5_1_20230716.zip)
It works fine.

**Comment by ruyo** [comment]
Thanks for the report.
Fixed. Please try using the latest version.

**Comment by Owlcean** [comment]
> Thanks for the report. Fixed. Please try using the latest version.

Thanks for reply!I test the latest version and it works fine.

**Comment by Owlcean** [comment]
> Thanks for the report. Fixed. Please try using the latest version.

would u mind releasing the latest source code?which might be there I suppose:https://github.com/ruyo/UnrealEngine_VRM4UPlugin/tags

**Comment by ruyo** [comment]
I added tag.
Thanks.

**Comment by Owlcean** [comment]
> I added tag. Thanks.

Got it.Thanks!

**Comment by Owlcean** [comment]
>
