### ISSUE TITLE
UE4.25、UE4.24のゲームが起動できない

### ISSUE THREAD

**Issue by monpoke8888** [ruyo/VRM4U#31]
こんにちは、UE4.25とUE4.24でWindows64-bitパッケージしてみたところ、パッケージは成功するもののgameが起動できない現象がおきましたのでご報告いたします。
なお、UE4.23とUE4.22では問題なくパッケージできるようです。

サードパーソンにVRM4Uを入れてパッケージする。

VRM4U-20200611

UE4.25でゲーム起動時のエラー
![image](https://user-images.githubusercontent.com/56508883/85553529-01689180-b65f-11ea-8a1d-96313febd560.png)

UE4.24はメッセージは特にでないでそのままゲームが起動しないという状況でした。

**Comment by ruyo** [comment]
報告ありがとうございます。

私の手元で試した限りでは、UE4.25でPKG作成、起動、ランタイムロードの動作　まで確認できています。
環境の問題かもしれません。

お手すきの時で良いので、停止時のログを添付いただけるとありがたいです。
確認済と思いますが、念の為以下の手順で最新のソースコードを適用し、
https://ruyo.github.io/VRM4U/03_exe/
DevelopかDebugのPKGで起動してください。
MyProject/Saved/Logs  にログが出力されます。

よろしくおねがいします。

**Comment by monpoke8888** [comment]
返信ありがとうございました。
最新モジュールといただいた手順でUE4.24、UE4.25ともPKGできました！

原因としては、ソースフォルダのコピーだけしており。
UE4.24、UE4.25でC++のプロジェクトを作成をしておりませんでした。

クローズいたします。
