### ISSUE TITLE
After the project is packaged, the outline is not displayed normally

### ISSUE THREAD

**Issue by byykt** [ruyo/VRM4U#312]
**Describe the bug**
I only enabled Vrm4u in the empty project, and I tried 1 and 5 for the model outline, but none of them can be displayed normally after packaging

**Screenshots, log**
<img width="582" alt="3c3e34052c5ddba83f4d8ab1b0918a0" src="https://github.com/ruyo/VRM4U/assets/138005913/174f6c9b-d209-4604-a0d9-dc8a2117e921">
<img width="1072" alt="ed245a552bf77b2185833fe6289e642" src="https://github.com/ruyo/VRM4U/assets/138005913/7cae3748-ee97-4ddc-b3b6-45675c5f2c01">

**UnrealEngine Version:**
UE5.1

**Additional context**

**Comment by ruyo** [comment]
Hi.
As far as I have tried, the outlines appear correctly in PKG.
Just for the sake of it, try using the third person template.
It may make a difference depending on the drawing settings and quality.

**Comment by byykt** [comment]
![image](https://github.com/ruyo/VRM4U/assets/138005913/483e876d-76b7-41cd-9f5e-6697bdc70d66)
The problem is solved. I am not sure if I am the only one who has this problem. In fact, I need to change the color here to see it after packaging.
