### ISSUE TITLE
[5.3] Mac M1 VRM failed to Load VRMMeta correctly

### ISSUE THREAD

**Issue by reforia** [ruyo/VRM4U#321]
Sorry for my Japanese, it was auto translated by AI :D

First of all, thank you so much for the awesome work here!
まず初めに、この素晴らしい作品に対して心から感謝します！

**Describe the bug**
When using VRM4U on Mac M1 Arm64 Unreal 5.3, while importing the character into the scene, the property window failed to read any vrmmeta data. (assimp are compiled with arm64 architecture) Open the plugin's content map and characters are all working properly.

バグの説明
Mac M1 Arm64 Unreal 5.3でVRM4Uを使用していると、シーンにキャラクターをインポートする際、プロパティウィンドウがvrmmetaデータを読み取ることができません。（assimpはarm64アーキテクチャでコンパイルされています）プラグインのコンテンツマップとキャラクターはすべて正常に動作しています。

After a bit investigation, I found the problem happens at 
少し調査したところ、問題が発生するのは以下の部分です。

`LoadBPFunctionLibrary.cpp
void ULoaderBPFunctionLibrary::SetImportMode(bool bIm, class UPackage *p) (Ln.412):`

`mScenePtr = mImporter.ReadFileFromMemory(Res.GetData(), Res.Num(),
			aiProcess_Triangulate | aiProcess_MakeLeftHanded | aiProcess_CalcTangentSpace | aiProcess_GenSmoothNormals | aiProcess_OptimizeMeshes,
			e.c_str());`

Where the mScenePtr will be able to get a proper pointer, however the mVRMMeta returned 0x1b1b1b0000000000, and the later  parts of the data are all invalid, as if some data are loaded with wrong offset
ここでmScenePtrは適切なポインタを取得できますが、mVRMMetaは0x1b1b1b0000000000を返し、その後のデータの部分はすべて無効です。まるで一部のデータが間違ったオフセットでロードされたかのようです。
画像
![image](https://github.com/ruyo/VRM4U/assets/11989463/fa34d1a2-88ce-4357-a56c-a1214d34878a)

I also observed that the mName has an extremely long length being loaded, feels like the VRMMeta data part gets skipped while loading
また、mNameが非常に長い長さでロードされていることも確認しました。
![image](https://github.com/ruyo/VRM4U/assets/11989463/7e8ead11-3f72-4b78-b681-0d5390f3eb87)

I know that you prob. don't have an Apple Sillicon at hand at this moment to test, but maybe you have some ideas of what it could possible be caused of and I can try to investigate it further, thanks a lot for any help!
現在、お手元にApple Siliconがないかもしれませんが、何が原因である可能性があるかについて何かアイデアがあれば、さらに調査を試みたいと思います。どうぞよろしくお願いします！

**Comment by reforia** [comment]
It's the same issue as 
Failed to create libassimp.a in MacOS #317

**Comment by madhavhaldia** [comment]
Is this an Issue with Apple silicon or MacOS in general because I get the same issue on x86 Macbooks as well.

**Comment by reforia** [comment]
I'm not sure, I feel it might be a general issue rather than apple sillicon

At this moment what I found in my investigation is the pScene->mName has loaded a huge chunk of data, while since the InternalReadFile function doesn't load the data in a sequence order like bytestream deserialization process and instead, the vrm data are essentially a gltf file which is essentially a json file. So technically it shouldn't be a wrong offset of the reader pointer issue.

With, if Windows doesn't have this issue, then I was suspecting if it could be the asset.Load(pFile, GetExtension(pFile) == "glb" || GetExtension(pFile) == "vrm") that caused a problem, like a wrong intendent, decoding method, etc. Since literally the first thing it tries to load is to load the pScene->mName = asset.scene->name;
`// read the asset file
    glTF2::Asset asset(pIOHandler, static_cast<rapidjson::IRemoteSchemaDocumentProvider *>(mSchemaDocumentProvider));
    //asset.Load(pFile, GetExtension(pFile) == "glb");
    asset.Load(pFile, GetExtension(pFile) == "glb" || GetExtension(pFile) == "vrm");
    if (asset.scene) {
        pScene->mName = asset.scene->name;
    }`
![image](https://github.com/ruyo/VRM4U/assets/11989463/a98b32b9-8516-4446-9e00-12bb480d572c)

**Comment by reforia** [comment]
> I'm not sure, I feel it might be a general issue rather than apple sillicon
> 
> At this moment what I found in my investigation is the pScene->mName has loaded a huge chunk of data, while since the InternalReadFile function doesn't load the data in a sequence order like bytestream deserialization process and instead, the vrm data are essentially a gltf file which is essentially a json file. So technically it shouldn't be a wrong offset of the reader pointer issue.
> 
> With, if Windows doesn't have this issue, then I was suspecting if it could be the `asset.Load(pFile, GetExtension(pFile) == "glb" || GetExtension(pFile) == "vrm") ` that caused a problem, like a wrong intendent, different decoding method, accidentally missed a terminate symbol for the data,etc. Since literally the first thing it tries to load is to load the pScene->mName = asset.scene->name;
> 
> ![image](https://user-images.githubusercontent.com/11989463/271200977-a98b32b9-8516-4446-9e00-12bb480d572c.png)
> 
> But so far I don't have an answer yet, and I don't know where to see these ASSIMP_LOGs being logged out, if anyone know where these in lib log will be printed that will be super helpful

I'm not sure, I feel it might be a general issue rather than apple sillicon

At this moment what I found in my investigation is the pScene->mName has loaded a huge chunk of data, while since the InternalReadFile function doesn't load the data in a sequence order like bytestream deserialization process and instead, the vrm data are essentially a gltf file which is essentially a json file. So technically it shouldn't be a wrong offset of the reader pointer issue.

With, if Windows doesn't have this issue, then I was suspecting if it could be the
asset.Load(pFile, GetExtension(pFile) == "glb" || GetExtension(pFile) == "vrm") 
that caused a problem, like a wrong intendent, different decoding method, accidentally missed a terminate symbol for the data,etc. Since literally the first thing it tries to load is to load the pScene->mName = asset.scene->name;

image

But so far I don't have an answer yet, and I don't know where to see these ASSIMP_LOGs being logged out, if anyone know where these in lib log will be printed that will be super helpful

**Comment by reforia** [comment]
> Is this an Issue with Apple silicon or MacOS in general because I get the same issue on x86 Macbooks as well.

I'm not sure, I feel it might be a general issue rather than apple sillicon

At this moment what I found in my investigation is the pScene->mName has loaded a huge chunk of data, while since the InternalReadFile function doesn't load the data in a sequence order like bytestream deserialization process and instead, the vrm data are essentially a gltf file which is essentially a json file. So technically it shouldn't be a wrong offset of the reader pointer issue.

With, if Windows doesn't have this issue, then I was suspecting if it could be the
asset.Load(pFile, GetExtension(pFile) == "glb" || GetExtension(pFile) == "vrm") 
that caused a problem, like a wrong intendent, different decoding method, accidentally missed a terminate symbol for the data,etc. Since literally the first thing it tries to load is to load the pScene->mName = asset.scene->name;

image

But so far I don't have an answer yet, and I don't know where to see these ASSIMP_LOGs being logged out, if anyone know where these in lib log will be printed that will be super helpful

**Comment by madhavhaldia** [comment]
I rebuilt assimp in debug. When importing the exception is thrown here indicating a JSON parse error. 

![Screenshot 2023-09-28 at 1 43 14 PM](https://github.com/ruyo/VRM4U/assets/60776535/cf1e86ad-d3a8-4165-a062-449b945a14e9)

**Comment by reforia** [comment]
> I rebuilt assimp in debug. Looks like an issue with rapidjson reading the file.
> 
> ![Screenshot 2023-09-28 at 1 58 56 PM](https://user-images.githubusercontent.com/60776535/271221161-f56bd2c0-ec6f-4ac5-a739-d896c6aec6cc.png)

Weird, this error is at ln.1205 which exist in glTFAsset.ini rather than glTF2Asset.ini, but the asset type is glTF2::Asset and the VRMMeta is GLTF2VRMMetadata, seems it's reading a glTF2 file using glTF config? Maybe that's where the problem is

**Comment by madhavhaldia** [comment]
> > I rebuilt assimp in debug. Looks like an issue with rapidjson reading the file.
> > ![Screenshot 2023-09-28 at 1 58 56 PM](https://user-images.githubusercontent.com/60776535/271221161-f56bd2c0-ec6f-4ac5-a739-d896c6aec6cc.png)
> 
> Weird, this error is at ln.1205 which exist in glTFAsset.inl rather than glTF2Asset.inl, but the asset type is glTF2::Asset and the VRMMeta is part of GLTF2VRMMetadata, seems it's reading a glTF2 file using glTF config? Maybe that's where the problem is


Probably the case. Doesn't explicitly use gltf loader but falls back onto auto detection of format.

![Screenshot 2023-09-28 at 2 55 31 PM](https://github.com/ruyo/VRM4U/assets/60776535/3d2dec16-01fd-4935-a5a2-36d8581c8b09)

**Comment by reforia** [comment]
> > > I rebuilt assimp in debug. Looks like an issue with rapidjson reading the file.
> > > ![Screenshot 2023-09-28 at 1 58 56 PM](https://user-images.githubusercontent.com/60776535/271221161-f56bd2c0-ec6f-4ac5-a739-d896c6aec6cc.png)
> > 
> > 
> > Weird, this error is at ln.1205 which exist in glTFAsset.inl rather than glTF2Asset.inl, but the asset type is glTF2::Asset and the VRMMeta is part of GLTF2VRMMetadata, seems it's reading a glTF2 file using glTF config? Maybe that's where the problem is
> 
> Probably the case. Doesn't explicitly use gltf loader but falls back onto auto detection of format. While doing this, it encounters GLTF before GLTF2 and breaks out. This is why it is using GLTF instead of GLTF2. Maybe this explains why the pointers don't point to vrmMeta because it is implemented for GLTF2.
> 
> ![Screenshot 2023-09-28 at 2 55 31 PM](https://user-images.githubusercontent.com/60776535/271236830-3d2dec16-01fd-4935-a5a2-36d8581c8b09.png)

Right, I force nuked the gltf related stuff and rebuild assimp again and indeed the pScene is nullptr now, after a bit more investigation it looks there's nothing in the possibleImporters array, still investigating which part messed up but I think we are pretty close

**Comment by madhavhaldia** [comment]
https://github.com/ruyo/VRM4U/issues/321#issuecomment-1738848901

Can you look into the GetExtensions method? I can't seem to figure out how it pulls the extensions supported.

**Comment by reforia** [comment]
https://github.com/ruyo/VRM4U/issues/321#issuecomment-1738882664

I think I've figured it out (Maybe.... waiting for a last compile...)

Will reply back if it's a go or a nvm lol

**Comment by reforia** [comment]
Damn... I think I got a good and bad news...

Good news is seems the GetExtensionList() is querying the data from GetInfo(), so just add vrm in glTF2Importer.cpp (ln. 105)

And then the Scene ptr is no longer nullptr, and I checked vrm extension is indeed valid now, since I already nuked whole glTF so I'm pretty sure it's now using glTF2

Bad news is... still... the cursed 0x1b1b1b0000000000

**Comment by madhavhaldia** [comment]
Hmm :( Weirdly though, the ReadFileFromMemory has an address for vrmMeta up until the point it return the value, IDK why this suddenly becomes invalid address after returning the value.


![Screenshot 2023-09-28 at 5 24 37 PM](https://github.com/ruyo/VRM4U/assets/60776535/d0e2562c-44f9-4167-88c0-744e84fa4710)

**Comment by ruyo** [comment]
Thanks for looking into this. My Mac is too old to compile UE, so I appreciate the information.

The mVRMMeta allocates memory as a C++ class in assimp. My guess is that the problem occurs when I try to cast the data allocated by lib and use it on the app side.

I am planning to migrate VRMMeta generation to the app side soon to support VRM1. I think I will be able to work around this error in the next few days.

**Comment by reforia** [comment]
> Thanks for looking into this. My Mac is too old to compile UE, so I appreciate the information.
> 
> The mVRMMeta allocates memory as a C++ class in assimp. My guess is that the problem occurs when I try to cast the data allocated by lib and use it on the app side.
> 
> I am planning to migrate VRMMeta generation to the app side soon to support VRM1. I think I will be able to work around this error in the next few days.

Thank you so much!!

**Comment by madhavhaldia** [comment]
Thanks a lot @ruyo @reforia , I managed to get this working for M1 except for the fact that Material instances aren't being created. All textures thumbnails and other stuff are getting imported. I used the GetOrphanedScene after calling the ReadFileFromMemory instead of using the value returned by the function. 

Idk if this would be relevant with what you have planned @ruyo

**Comment by reforia** [comment]
Thanks a lot for finding a walk around! @madhavhaldia i will try your solution soon

**Comment by madhavhaldia** [comment]
> Thanks a lot for finding a walk around! @madhavhaldia i will try your solution soon

Also, i forgot to mention that I turned of compiler optimisation in cmake

**Comment by reforia** [comment]
<img width="988" alt="image" src="https://github.com/ruyo/VRM4U/assets/11989463/b46b1eba-cea9-404a-9ac0-a7dd1bfde9c6">
 @madhavhaldia Hi, do you mean like this?

**Comment by madhavhaldia** [comment]
> <img alt="image" width="988" src="https://user-images.githubusercontent.com/11989463/271480595-b46b1eba-cea9-404a-9ac0-a7dd1bfde9c6.png"> @madhavhaldia Hi, do you mean like this?


Yes

**Comment by reforia** [comment]
Hmm, I'm still getting the same error, maybe there're some more underlying problem with Arm64 then

**Comment by madhavhaldia** [comment]
> Hmm, I'm still getting the same error, maybe there're some more underlying problem with Arm64 then

Check if you have the same thing
`UVrmLicenseObject *ULoaderBPFunctionLibrary::GetVRMMeta(FString filepath)
{
	std::string file;
#if PLATFORM_WINDOWS
	file = utf_16_to_shift_jis(*filepath);
#else
	file = TCHAR_TO_UTF8(*filepath);
	UE_LOG(LogVRM4ULoader, Warning, TEXT("tesgtFilepath"));
	UE_LOG(LogVRM4ULoader, Warning, TEXT("filepath is = %s"), *filepath);
#endif

	Assimp::Importer mImporter;
	const aiScene *mScenePtr = nullptr; // delete by Assimp::Importer::~Importer

	TArray<uint8> Res;
	if (FFileHelper::LoadFileToArray(Res, *filepath))
	{
	}
	const FString ext = FPaths::GetExtension(filepath);
#if PLATFORM_WINDOWS
	std::string e = utf_16_to_shift_jis(*ext);
#else
	std::string e = TCHAR_TO_UTF8(*ext);
#endif

	mImporter.ReadFileFromMemory(Res.GetData(), Res.Num(),
								 aiProcess_Triangulate | aiProcess_MakeLeftHanded | aiProcess_CalcTangentSpace | aiProcess_GenSmoothNormals | aiProcess_OptimizeMeshes,
								 e.c_str());

	mScenePtr = mImporter.GetOrphanedScene();

	// UE_LOG(LogVRM4ULoader, Log, TEXT("VRM:(%3.3lf secs) ReadFileFromMemory"), FPlatformTime::Seconds() - StartTime);

	if (mScenePtr == nullptr)
	{
		return nullptr;
	}
	UTexture2D *NewTexture2D = nullptr;

	VRM::VRMMetadata *meta = reinterpret_cast<VRM::VRMMetadata *>(mScenePtr->mVRMMeta);
`

**Comment by madhavhaldia** [comment]
> Hmm, I'm still getting the same error, maybe there're some more underlying problem with Arm64 then

So this has nothing to do with changing the code just build assimp using the following command (turning compiler optimisations off). It'll throw some errors regarding snprintf, just go about fixing them and you'll be good.

`cmake CMakeLists.txt -DLIBRARY_SUFFIX:STRING= -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-O0 -DCMAKE_C_FLAGS=-O0`

**Comment by reforia** [comment]
Thanks a lot! I wasn't with my Mac today but yeah I was also suspecting the optimization thing rather than the orphaned scene cuz I changed the code and observing the call stack seems the address doesn't change at all. Also I've noticed that the address is actually changing based on where my breakpoint is, so if I try to observe it the address would be fixed but if not observing it it will be 1b1b1b0000 so effectively a heissenbug. Given there doesn't seem to involving any multithreading so data racing is not the case. Leaving compiler optimization a huge suspection

**Comment by madhavhaldia** [comment]
> Thanks a lot! I wasn't with my Mac today but yeah I was also suspecting the optimization thing rather than the orphaned scene cuz I changed the code and observing the call stack seems the address doesn't change at all. Also I've noticed that the address is actually changing based on where my breakpoint is, so if I try to observe the pointer initialization process then the address would be fixed but if not observing it it will be 1b1b1b0000 so effectively a heissenbug. Given there doesn't seem to involving any multithreading so data racing is not the case. And 1b1b1b0000 is just too specific and too stable to be a certain hardware issue or random undefined behavior issue as it seems to be happen on all macOS. Leaving compiler optimization a huge suspection

True, I to wasn't convinced with the GetOrphanedScene stuff but I was moving fast so shared everything here. Hope this works out for everyone.

**Comment by reforia** [comment]
I donno what's going wrong but I'm still having the same issue with the new config turning optimization off.
I was using JetBrain rider but I don't feel it's a compiler issue any more, cuz technically when building the config with debug previously technically we've already turned off optimization if I understand correctly

But glad it's been working out for you and huge thanks for posting the process here :D, I guess I will wait for the refactored version then but hopefully this walkaround will work for others

**Comment by madhavhaldia** [comment]
> I donno what's going wrong but I'm still having the same issue with the new config turning optimization off. I was using JetBrain rider but I don't feel it's a compiler nor IDE issue any more, cuz technically when building the config with debug previously technically we've already turned off optimization if I understand correctly
> 
> But glad it's been working out for you and huge thanks for posting the process here :D, I guess I will wait for the refactored version then but hopefully this walkaround will work for others

Hmm, now that you mentioned it, yes debug mode works without any optimisations. This is so weird, I guess I'll trace back my steps and see what exactly did this.

**Comment by reforia** [comment]
Just an update... So I managed to get it working... Material Instances are also auto created just fine
![image](https://github.com/ruyo/VRM4U/assets/11989463/829e5ba2-9623-423f-8542-147eee4151ba)

![image](https://github.com/ruyo/VRM4U/assets/11989463/ae3cc97a-fcca-49c9-9b9d-a89793072876)

But I don't have a 100% conclusion on why it doesn't work at the first place.

Here's my deduction: the scene.h holds a ptr of mVRMMeta just as a wrapper to pass the data to app side. However, instead of including assimp/vrm/vrmmeta.h and explicitly give it VRM::VRMMetadata* type, it was stored as void*, prob the intention was to decouple the linkage of the vrmmeta at the aiscene side.

However, that would require the rest usage of thie vrmmeta to be all converted with reinterpret_cast<VRM::VRMMetadata*> I've put a data breakpoint at the initial CreateClone() method (watchpoint, turns out it's actually supported on MacOS now with LLDB) But I didn't really catch a write operation of it, so I was guessing maybe it's that part of the memory that gets override by another operation later, without explicitly mark an area of memory as certain type at early stage, maybe results in the compiler think the chunk of memory are actually a valid memory to write in, hence allowed another writing operation to it, which the operation effectively bypassed the pointer actually pointed to this memory (since a void*)

So my solution is just include "assimp/vrm/vrmmeta.h" in the scene.h
![image](https://github.com/ruyo/VRM4U/assets/11989463/587133af-3efa-4a89-adf7-2d1f89bc5c4f)

Then change the mVRMMeta type from void* to VRM::VRMMetadata*
![image](https://github.com/ruyo/VRM4U/assets/11989463/59a32ac4-4547-424d-be73-b70a30c89cd0)

Get rid of all the reinterpret_cast to it later in the code. (Since it's already a VRM::VRMMetadata type)

Also I modified the ReleaseVRMMetadata() function, it originally takes in a void* p param and I changed it to VRM::VRMMetadata*& meta
![image](https://github.com/ruyo/VRM4U/assets/11989463/395b1f5d-0a6c-4569-bf8f-ffdaa3b1eef2)

Fix all related compile bugs
And recompile everything and it worked fine for me.

**Comment by reforia** [comment]
And btw, in cmake we can use --DASSIMP_WARNINGS_AS_ERRORS=OFF to get rid of compiler error caused by the deprecation of those sprintf API

**Comment by ruyo** [comment]
Hi.
The latest version fixes a runtime error on Macs.
If you would like to try it out, please refer to the new documentation to set it up.
https://ruyo-github-io.translate.goog/VRM4U/03_mac/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja
Thanks

**Comment by reforia** [comment]
The latest plugin has fixed this issue! Thanks a lot for the hard work!!
