### ISSUE TITLE
[UE5.1]  Project packaging error(windows)

### ISSUE THREAD

**Issue by vtgchey** [ruyo/VRM4U#323]
**Describe the bug**

When I package a project(for windows) turned on vrm4u 5.1, it fails with the log below.(When I turn off vrm4u in the plugins menu, packaging goes well.)

**Screenshots, log**

![ScreenShot](https://github.com/ruyo/VRM4U/assets/145952073/43d20944-a577-4b06-9aac-f3de9f70e122)

[Vstar.log](https://github.com/ruyo/VRM4U/files/12813636/Vstar.log)
-> Path : Vstar/Saved/Logs/Vstar.log

[UBT-Vstar-Win64-Development.txt](https://github.com/ruyo/VRM4U/files/12813826/UBT-Vstar-Win64-Development.txt)
-> Path : C:\Users\tgchey\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_5.1

**UnrealEngine Version:**

UE5.1.1

**Comment by ruyo** [comment]
Hi.
Please refer here for the source of the plugin
https://ruyo-github-io.translate.goog/VRM4U/03_exe/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja

**Comment by vtgchey** [comment]
Thank you I solved this! :)
