### ISSUE TITLE
[UE5.3] Error: Assertion failed: MatchingInput を出力してクラッシュする

### ISSUE THREAD

**Issue by forest00** [ruyo/VRM4U#331]
お世話になっております
私たちのプロジェクトにてVRM4Uを導入した際、マテリアルを編集中にクラッシュが発生しました
再現手順とログを共有します

再現手順
1.スターターコンテンツなしの空プロジェクトを作成する
2.ダウンロードしたVRM4U(tag:20231008)を追加する
3.エディターを立ち上げる
4.M_VrmMToonBaseOpaqueマテリアルを開き、保存する
5.MI_VrmMToonOptSSSを開く
6.mtoon_RimFresnelPowerをマウスでクリックし、エディターUIに従って左右に動かし続ける

**Screenshots, log**
<img width="1286" alt="スクリーンショット 2023-10-23 233834" src="https://github.com/ruyo/VRM4U/assets/48117586/af3a75d1-6ee1-43c5-92dd-c37bb594f23a">
<img width="560" alt="スクリーンショット 2023-10-23 234043" src="https://github.com/ruyo/VRM4U/assets/48117586/e5142984-f809-4e5d-a420-adc54c164418">
[VRM4U_Test.log](https://github.com/ruyo/VRM4U/files/13072262/VRM4U_Test.log)

**UnrealEngine Version:**
UE5.3.1

**使用Plugin:**
https://github.com/ruyo/UnrealEngine_VRM4UPlugin/tree/20231008

**Comment by ruyo** [comment]
報告ありがとうございます。
MaterialFunctionの繋ぎ方にまずい部分があったようです。ソース側のリポジトリでは修正済です。
次回リリースにて反映されます。おそらく数日中にリリースできると思います。

**Comment by forest00** [comment]
こちらの件、ご対応いただきありがとうございます
https://github.com/ruyo/UnrealEngine_VRM4UPlugin/releases/tag/20231030を取得し、何度かテストさせていただいたところ、、クラッシュが発生しなくなっているようでした
