### ISSUE TITLE
Error packaging in 4.26.2 due to migrated repository.

### ISSUE THREAD

**Issue by Keyotine** [ruyo/VRM4U#332]
Apologies in advance if this issue has already been addressed, but I followed a guide on packaging and already downloaded the source code plugin. I had an issue where the project wouldn't open due to missing files for "VRMCapture" but redownloading and doing a clean install seemed to work. Now i get this error when packaging:

Error: static_assert failed "***This repository has been migrated***  use https://github.com/ruyo/VRM4U.git  detail:https://github.com/ruyo/VRM4U"

Even when downloading the plugin on the link, I get a list of more errors that prevent my project from opening.

**Comment by Keyotine** [comment]
Nevermind, I figured out you have to overwite the original plugin with the link from the master files.

**Comment by Keyotine** [comment]
Nevermind, I figured out you have to overwite the original plugin with the link from the master files.

**Comment by ruyo** [comment]
VRM4U repository has been moved to the Public side. Please use the Public side from now on.
Sorry the documentation is not up to date.
You can comment out static_assert for temporary use.
Thanks.
