### ISSUE TITLE
コントロールリグへのモーフのベイクができない

### ISSUE THREAD

**Issue by figihiuy** [ruyo/VRM4U#343]
コントロールリグへのモーフのアニメーションベイクができません。
キーは入りますが数値が変動していないようです。

UE5.3
VRM4U　20231126

**Comment by ruyo** [comment]
どのリグを利用しているでしょうか？
CR_VRoidSimpleUE5All であればモーフも動作すると思います。
他はあまりメンテナンスできていません。。ので近々削除予定です。

**Comment by figihiuy** [comment]
ありがとうございます。
CR Moprhを使っていたのですがCR_VRoidSimpleUE5Allを利用したところ動作いたしました。
