### ISSUE TITLE
BP_VrmCharacterBaseでランタイムリターゲットしたさいにPlay Anim Montageをうごかしたい。

### ISSUE THREAD

**Issue by monpoke8888** [ruyo/VRM4U#35]
こんにちは、はるべえさん！
BP_VrmCharacterBaseを利用してランタイムリターゲットでPlay Anim Montageをうごかしたいのですが利かないようです。
BP_VrmCharacterBaseからPlay Anim Montageノードをうごかせるような技などありますでしょうか。

なお、Play Animationはできそうです。

**Comment by ruyo** [comment]
こんにちは

ランタイムリターゲットでは、SkeletalMesh_retargetSrc にアニメーションを渡す必要があります。
以下のように設定すれば、Montageの再生と時間の取得ができると思います。
利用するMontageはVRoidSimpleのSkeletonで作成ください。

補足ですがデバッグとして、retargetSrcのVisibleをONにしておくとアニメーションが実際に再生できているか確認しやすいです。

![image](https://user-images.githubusercontent.com/6472835/88091721-69f94e80-cbca-11ea-9d52-3416ac1c5c96.png)

![image](https://user-images.githubusercontent.com/6472835/88092515-8f3a8c80-cbcb-11ea-9faa-7ae9540a3639.png)

**Comment by monpoke8888** [comment]
返信ありがとうございます！
OKとNGの使い方がわかってすっきりしました。

おしえていただいたPlay AnimationとGet Play Lengthをつかって
画像のような組み方で再生できました。

＃Get Play Lengthがわからず各アニメーションで終了時間をベタ打ちしており
＃苦戦しておりましたので助かりました！ありがとうございます！

この組み方の罠としてはPlay AnimationのあとにTポーズになってしまうようで
Anim Instansでセットしなおしが必要でアニメのつながりが少々不自然となります
これはエフェクトなどでごまかそうとおもいます。。

![image](https://user-images.githubusercontent.com/56508883/88114008-eea99400-cbed-11ea-957e-96ce684bb9da.png)
