### ISSUE TITLE
源码版VRM插件在UE5.3.2打包失败

### ISSUE THREAD

**Issue by BlackSaber0** [ruyo/VRM4U#350]
使用的是源码版VRM4U_5_3_20231126插件，测试新建了一个UE5.3.2空的项目，只添加了VRM插件依旧打包失败。下面是报错截图
![VRM5 3](https://github.com/ruyo/VRM4U/assets/147738147/f7ad63e3-2fc5-4df6-93a7-733aaaeaacd1)
还测试源码版VRM4U_5_3_20231105，VRM4U_5_3_20231030，VRM4U_5_3_20231008，其中只有VRM4U_5_3_20231030报错最少截图
<img width="1257" alt="VRM10 30" src="https://github.com/ruyo/VRM4U/assets/147738147/6333aaac-bf87-4d2f-a69a-5448207e26cf">

**Comment by BlackSaber0** [comment]
找到了解决办法，将Plugins\VRM4U\Content\Util\Actor 文件夹下的latest这个文件夹删掉即可

**Comment by ruyo** [comment]
Hi.
Below the "latest" folder you will find assets that depend on a specific version or plugin. If you do not need them, please delete them.
