### ISSUE TITLE
Migrating to UE5.3

### ISSUE THREAD

**Issue by xford450** [ruyo/VRM4U#352]
Hello! I have a project on UE4.24 and I transferred it to UE5.3 and there is a problem that the new version of the engine does not show morphs on models imported in the old version of the engine. Is there any way to fix this?

**Comment by kayela-c** [comment]
Maybe, and I'm not sure if this will work,  try uninstalling the plugin in the 5.3 engine and reinstalling the plugin using the 5.3 version of the plug-in?

**Comment by xford450** [comment]
> Maybe, and I'm not sure if this will work, try uninstalling the plugin in the 5.3 engine and reinstalling the plugin using the 5.3 version of the plug-in?

I have been using the latest version of the VRM4U plugin for 5.3.

When I export a model from an older version of the engine and import into 5.3, it works. If I export the same model using 5.3 and re-import, the morphs are not imported.

**Comment by ruyo** [comment]
Hi.
Re-import the VRM model with the latest plug-ins.
Data using older plug-ins may lack internal data. If you change the version, it may not be loaded correctly.
Thanks.
