### ISSUE TITLE
failed import, unknown extension 

### ISSUE THREAD

**Issue by TresnaNeedHelp** [ruyo/VRM4U#359]
hello Ruyo
im trying to use your VRM4U plugin but i always ended up like this

![image](https://github.com/ruyo/VRM4U/assets/140897290/ec62e7f5-afde-4931-9326-4a89fa3b3e1e)

im using UE version 4.27.2 and i already extract it to my ue folder (D:\UE_4.27\Engine\Plugins) and my project files (C:\MyDocuments\MyProject\Plugins). and i already enable the "allow all assimp format" but it still didn't work and keep saying "..unknown extension"

i also trying to use version 4.26 with plugin version 4.26 but it still ended up like the image.
i hope you can help me Ruyo, thank you!

**Comment by HanX1ao** [comment]
me too. this issue is also troubling me, it always says"unknown extension.vrm"

**Comment by Cleideson** [comment]
Try delete the folder Binaries, and open again the .uproject to rebuild

**Comment by HanX1ao** [comment]
> Try delete the folder Binaries, and open again the .uproject to rebuild

Tried it, it didn't work at all, after delete. Binaries folder, the .uproject cannot be opened directly

**Comment by ruyo** [comment]
Sorry, there was a bug in the release script.
Fixed in 20240320.

**Comment by TresnaNeedHelp** [comment]
thank you for responding Ruyo, now i can use your plugin without any problem
