### ISSUE TITLE
Package issue

### ISSUE THREAD

**Issue by reapera** [ruyo/VRM4U#36]
Hi @ruyo , 
I'm having trouble when packaging

`LogUObjectHash: Compacting FUObjectHashTables data took   0.65ms
LogMainFrame: Project requires temp target (VRM4U plugin is enabled)
LogLauncherProfile: Unable to use promoted target - L:/ProjectGames/UnrealEngine4/Vroid/Binaries/Android/UE4Game.target does not exist.
UATHelper: Packaging (Android (ETC2)): Running AutomationTool...
UATHelper: Packaging (Android (ETC2)): Parsing command line: -ScriptsForProject=L:/ProjectGames/UnrealEngine4/Vroid/Vroid.uproject BuildCookRun -nocompileeditor -installed -nop4 -project=L:/ProjectGames/UnrealEngine4/Vroid/Vroid.uproject -cook -stage -archive -archivedirectory=L:/ProjectGames/UnrealEngine4/Dino -package -ue4exe=F:\Games\Epic\UE_4.25\Engine\B
inaries\Win64\UE4Editor-Cmd.exe -pak -prereqs -nodebuginfo -targetplatform=Android -cookflavor=ETC2 -build -clientconfig=Development -utf8output
UATHelper: Packaging (Android (ETC2)): Setting up ProjectParams for L:\ProjectGames\UnrealEngine4\Vroid\Vroid.uproject
UATHelper: Packaging (Android (ETC2)): WARNING: The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)
UATHelper: Packaging (Android (ETC2)): F:\Games\Epic\UE_4.25\Engine\Plugins\VRM4U\VRM4U.uplugin: warning: The 'Developer' module type has been deprecated in 4.24.
PackagingResults: Warning: The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)
PackagingResults: Warning: The 'Developer' module type has been deprecated in 4.24.
UATHelper: Packaging (Android (ETC2)): Vroid.uproject requires a temporary target.cs to be generated (VRM4U plugin is enabled)
UATHelper: Packaging (Android (ETC2)): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Android (ETC2)): Running: F:\Games\Epic\UE_4.25\Engine\Binaries\DotNET\UnrealBuildTool.exe Vroid Android Development -Project=L:\ProjectGames\UnrealEngine4\Vroid\Vroid.uproject  L:\ProjectGames\UnrealEngine4\Vroid\Vroid.uproject -NoUBTMakefiles  -remoteini="L:\ProjectGames\UnrealEngine4\Vroid" -skipdeploy -Manifest=L:\ProjectGames\Unrea
lEngine4\Vroid\Intermediate\Build\Manifest.xml -NoHotReload -log="C:\Users\faisa\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+Games+Epic+UE_4.25\UBT-Vroid-Android-Development.txt"
UATHelper: Packaging (Android (ETC2)):   WARNING: The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)
UATHelper: Packaging (Android (ETC2)):   F:\Games\Epic\UE_4.25\Engine\Plugins\VRM4U\VRM4U.uplugin: warning: The 'Developer' module type has been deprecated in 4.24.
PackagingResults: Warning: The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)
PackagingResults: Warning: The 'Developer' module type has been deprecated in 4.24.
UATHelper: Packaging (Android (ETC2)):   ERROR: Expecting to find a type to be declared in a module rules named 'VRM4U' in UE4Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
PackagingResults: Error: Expecting to find a type to be declared in a module rules named 'VRM4U' in UE4Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
UATHelper: Packaging (Android (ETC2)): Took 0.6310355s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Android (ETC2)): UnrealBuildTool failed. See log for more details. (C:\Users\faisa\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+Games+Epic+UE_4.25\UBT-Vroid-Android-Development.txt)
UATHelper: Packaging (Android (ETC2)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Android (ETC2)): BUILD FAILED
PackagingResults: Error: Unknown Error`

Tried packaging in android = fails
win64 = fails but I think its because I havent installed visual studio 2019 and C++, does it affects android packaging?

Steps I take:
1. put VRM4U release 20200725 to UE4 plugins
2. make games, build it, play it no problem (except android launch)
3. Put source folder from https://github.com/ruyo/UnrealEngine_VRM4UPlugin to UE4 plugins/VRM4U
4. still cannot package

Please help ya thanks!

**Comment by ruyo** [comment]
Hi.
You probably don't need Visual Studio.
Do you have an NDK installed that supports UE4.25?

See the following pages
https://www.unrealengine.com/en-US/tech-blog/updates-to-required-setup-for-android-ndk-21-in-unreal-engine-4-25?lang=en-US

Thanks.

**Comment by reapera** [comment]
I have followed that from the start, btw i also got this error on launch on my android devices if VRM4U is enabled

`LogPlayLevel: Completed Launch On Stage: Cooking in the editor, Time: 20.010450
LogPlayLevel: Running AutomationTool...
LogPlayLevel: Parsing command line: -ScriptsForProject=L:/ProjectGames/UnrealEngine4/Vroid/Vroid.uproject BuildCookRun -project=L:/ProjectGames/UnrealEngine4/Vroid/Vroid.uproject -noP4 -clientconfig=Development -serverconfig=Development -nocompile -nocompileeditor -installed -ue4exe=F:\Games\Epic\UE_4.25\Engine\Binaries\Win64\UE4Editor-Cmd.exe -utf8output -p
latform=Android -targetplatform=Android -cookflavor=ASTC -ini:Game:[/Script/UnrealEd.ProjectPackagingSettings]:BlueprintNativizationMethod=Disabled -map=/Game/EndlessRunner/Run -skipcook -CookInEditor -iterativecooking -compressed -iterativedeploy -stage -deploy -cmdline="/Game/EndlessRunner/Run -Messaging" -device=Android_ASTC@20314e0d -addcmdline="-Session
Id=E869C5A7441B50549D2D8C913AC2F1C9 -SessionOwner='faisa' -SessionName='Launch On Device'  " -run
LogPlayLevel: Setting up ProjectParams for L:\ProjectGames\UnrealEngine4\Vroid\Vroid.uproject
LogPlayLevel: Warning: WARNING: The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)
LogPlayLevel: Warning: F:\Games\Epic\UE_4.25\Engine\Plugins\VRM4U\VRM4U.uplugin: warning: The 'Developer' module type has been deprecated in 4.24.
LogPlayLevel: Vroid.uproject requires a temporary target.cs to be generated (VRM4U plugin is enabled)
LogPlayLevel: ********** STAGE COMMAND STARTED **********
LogPlayLevel: Error: ERROR: Stage Failed. Missing receipt 'L:\ProjectGames\UnrealEngine4\Vroid\Binaries\Android\Vroid.target'. Check that this target has been built.
LogPlayLevel: Completed Launch On Stage: Build Task, Time: 2.308996
LogPlayLevel:        (see C:\Users\faisa\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+Games+Epic+UE_4.25\Log.txt for full exception trace)
LogPlayLevel: AutomationTool exiting with ExitCode=103 (Error_MissingExecutable)
LogPlayLevel: Completed Launch On Stage: Deploy Task, Time: 0.000042
LogPlayLevel: BUILD FAILED
PackagingResults: Error: Launch failed! Missing UE4Game binary.
You may have to build the UE4 project with your IDE. Alternatively, build using UnrealBuildTool with the commandline:
UE4Game <Platform> <Configuration>`

![image](https://user-images.githubusercontent.com/18773603/88509863-2bb9c000-d00c-11ea-890a-19013f75c73f.png)

**Comment by reapera** [comment]
and this when packaging 
![image](https://user-images.githubusercontent.com/18773603/88510019-61f73f80-d00c-11ea-9fca-682a02ed9e8e.png)

**Comment by ruyo** [comment]
Just to be sure, are you able to package and launch Android without VRM4U?

I've confirmed that Android packaging and launch works on my UE4.24.
Probably UE4.25 is fine as well... but I haven't confirmed that it works because I don't have the environment in place.

**Comment by reapera** [comment]
Yes, I even tried to start a new project with ThirdPerson template and it works (with VRM4U disabled)
when I enable it and import some default Vroid VRMs I can no longer package the project, and got the same message as my other project

`UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   ERROR: Expecting to find a type to be declared in a module rules named 'VRM4U' in UE4Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
PackagingResults: Error: Expecting to find a type to be declared in a module rules named 'VRM4U' in UE4Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.`

Let me try on 4.24

**Comment by reapera** [comment]
I'm on 4.25.2 btw

**Comment by reapera** [comment]
tried in 4.24.3, got different error when trying to launch on windows
the steps I take to get this:
1. Make new c++ project 
2. get VRM4U release for 4.24 zip
3. put it on engine/plugins
4. import .vrm file
5. works!
6. tried to launch on windows
7. doesn't work, close epic, paste source folder from UnrealEngine_VRM4UPlugin-20200725 to engine/plugins/VRM4U
8. Got this error below

LogPlayLevel: Error:   ERROR: Missing precompiled manifest for 'VRM4U'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in VRM4U.build.cs to override.

**Comment by ruyo** [comment]
I tried it on 4.25.2 and confirmed that it can package and launch for Android. It also works with Launch directly from the editor.
It seems to be a difference in preferences. Is it possible to attach all the logs from package creation?

![image](https://user-images.githubusercontent.com/6472835/88569558-918e6200-d075-11ea-99c0-e7be665bbb96.png)

**Comment by reapera** [comment]
[Vroid_2.log](https://github.com/ruyo/VRM4U/files/4988397/Vroid_2.log)
 Log on Windows launch, then Android Launch, then Windows Launch again

[Vroid_Package.log](https://github.com/ruyo/VRM4U/files/4988408/Vroid_Package.log)
and the log on Android packaging and Windows packaging

nice model btw :D

**Comment by reapera** [comment]
also here the log on UnrealBuildTool failed. See log for more details. (C:\Users\faisa\AppData\Roaming\Unreal Engine\AutomationTool\Logs\F+Games+Epic+UE_4.25\UBT-Vroid-Win64-Development.txt)

[UBT-Vroid-Win64-Development.txt](https://github.com/ruyo/VRM4U/files/4988436/UBT-Vroid-Win64-Development.txt)
[UBT-Vroid-Android-Development.txt](https://github.com/ruyo/VRM4U/files/4988440/UBT-Vroid-Android-Development.txt)

**Comment by reapera** [comment]
btw after some googling I found this 
https://answers.unrealengine.com/questions/973380/error-expecting-to-find-a-type-to-be-declared-in-a-1.html
will try it now

**Comment by reapera** [comment]
aaaand now i got another different error 
[UBT-Vroid-Win64-Development.txt](https://github.com/ruyo/VRM4U/files/4988471/UBT-Vroid-Win64-Development.txt)

`UATHelper: Packaging (Windows (64-bit)):   ERROR: Missing precompiled manifest for 'VRM4U'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in VRM4U.build.cs to override.
PackagingResults: Error: Missing precompiled manifest for 'VRM4U'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in VRM4U.build.cs to override.`

**Comment by reapera** [comment]
I think I got it. after some things here and there I tried to look for all closed issue on this repo and try them all.
This is the one that really helpful for me https://github.com/ruyo/VRM4U/issues/2 plus make empty C++ class and then I rebuild them all on Visual Studio.
Now I can launch on windows. Gonna try to launch on android and package it as well
