### ISSUE TITLE
Can't package project in UE5.3 (PLEASE HELP FAST!!)

### ISSUE THREAD

**Issue by Nepharius1** [ruyo/VRM4U#361]
These are my errors when i try to build with Visual Studio and I can't figure out what to do.

![Screenshot (291)](https://github.com/ruyo/VRM4U/assets/80860053/eae45357-d18b-425f-aec7-864438a49fd2)

**Comment by ruyo** [comment]
Hi.
Please refer to this page to build.
If you get an error, please attach a log file.
https://ruyo-github-io.translate.goog/VRM4U/03_exe/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja

**Comment by Nepharius1** [comment]
> Hi. Please refer to this page to build. If you get an error, please attach a log file. https://ruyo-github-io.translate.goog/VRM4U/03_exe/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja

I followed those instructions and I still get the same error, what do you mean "attach a log file?" How do i do that?
