### ISSUE TITLE
Facial Expressions don't work after packaging.

### ISSUE THREAD

**Issue by Nepharius1** [ruyo/VRM4U#363]
I fixed all the errors with packaging, but after I packaged the game, none of the facial expressions are moving like they're suppose to.
In the editor it's not working, and I can't move them in the animation itself either.

She's suppose to have a surprised expression here. 

![image_2024-03-25_202044737](https://github.com/ruyo/VRM4U/assets/80860053/a7e85254-1115-49bd-95f2-f0ddf6eef314)

**Comment by ruyo** [comment]
Hi.
MorphTarget is working fine as far as I have tested.
Please check your SkeletalMesh.

**Comment by Nepharius1** [comment]
> Hi. MorphTarget is working fine as far as I have tested. Please check your SkeletalMesh.

Thank you. Is fixed
