### ISSUE TITLE
(UE5.4) Bang hair bones keep rotating(jittering) in the skeleton mesh editor and therefore hair is blown up and jittering on the forehead in rumtime

### ISSUE THREAD

**Issue by weirongsie** [ruyo/VRM4U#374]
**Describe the bug**
The character's bang looks fine in the UE editor but is blown up and jittering in run time
![in editor](https://github.com/ruyo/VRM4U/assets/20578177/8cf3270e-4221-4432-88e2-8b6810a1552d)
↑ in editor
![in runtime](https://github.com/ruyo/VRM4U/assets/20578177/98053248-7e18-432a-b0b8-d25955270a61)
↑ in runtime
So, I open the character's skeleton mesh and find that all the hair bones keep rotating(jittering) in the skeleton mesh editor.
(If you click the hair bones, its rotating value changes every second, and the reset rotation button doesn't work)
![vrm4u](https://github.com/ruyo/VRM4U/assets/20578177/eb9b9d90-2af2-4872-bfe9-f6f124b1cf54)

This character uses the default bang in VRoid. The bang initially has hair bones, I didn't modify the bones in VRoid.
Any help would be very appreciated!
Thank you for creating such a great plugin for us!

**UnrealEngine Version:**
UE 5.4.1 with vrm4u 20240516 release

**Comment by ruyo** [comment]
Hi.
It is an effect of VRMSpringBone, because VRM4U does not handle SpringBone correctly.

Please use VRM1 models or disable the setting from PostAnimBP.
<img width="1920" alt="image" src="https://github.com/ruyo/VRM4U/assets/6472835/a1252c68-7fd5-4a6c-a6ee-6a6343a8dcaf">

**Comment by weirongsie** [comment]
Thank you very much!
