### ISSUE TITLE
AttachMToonActorのアウトラインの問題

### ISSUE THREAD

**Issue by xizro345** [ruyo/VRM4U#380]
**Describe the bug**
AttachMToonActorを適用し、アウトラインを選択すると、アニメーションでは機能しません。また、Control Rigでも同様の問題が発生します。
モデルは主にシーケンサーで使用されます。(BPを使いません)
時々、エディターではアウトラインが正しく表示されるのに、レンダリング時に画像のような状態になります。

**Screenshots, log**
![immagine](https://github.com/ruyo/VRM4U/assets/171425302/fe38c959-80d3-437f-b68f-fc511f380943)
![immagine](https://github.com/ruyo/VRM4U/assets/171425302/0f315bf0-f8a3-43bf-a690-4bd3c1ee8d97)

**UnrealEngine Version:**
UE5.4.1とUE5.3.2
VRM4U Ver. 20240530
モデルは、VRM4Uの変更前にプロジェクトにインポートされた古いマテリアルシステムを使用しています。
問題は以前のバージョンのVRM4Uでは発生しませんでした。
**Additional context**
新しいプロジェクトでテストする機会がありませんでした。
VRM0とVRM1.0で問題が発生します。

更新 (2024/02/06): 新しくインポートしたモデル (UE5マテリアル、VRM0) でテストしたところ、動作するようです。
ただし、モデルを再インポートせずにこの問題を解決できる方法があるかどうかを知りたいです。

**Comment by ruyo** [comment]
20240606にて修正しました。ので差し替えてみてください。
アウトライン用のコンポーネントの挙動が変わってしまっていたのを対処してあります。

**Comment by xizro345** [comment]
お返事ありがとうございます。
確認しました。動作するようです。
バグレポートを閉じます。
