### ISSUE TITLE
Cook Process Failed

### ISSUE THREAD

**Issue by AlisonLuan** [ruyo/VRM4U#381]
**Describe the bug**
Missing content on COOK process.

**Screenshots, log**
_Warnings/errors on project load (maybe helps):_
[error on start.txt](https://github.com/user-attachments/files/15526319/error.on.start.txt)

_Warnings/errors on Cook command:_
[cooklog.txt](https://github.com/user-attachments/files/15526312/cooklog.txt)

_Highlight from my side, what maybe is the issue:_

PackagingResults: Error: Content is missing from cook. Source package referenced an object in target package but the target package was marked NeverCook or is not cookable for the target platform.

_and this_

UATHelper: Cooking (Windows): LogInit: Display: LogProperty: Error: FStructProperty::Serialize Loading: Property 'StructProperty /VRM4U/Util/Actor/latest/ABP_VRoidPostProcess.ABP_VRoidPostProcess_C:AnimGraphNode_LiveLinkPose'. Unknown structure.
UATHelper: Cooking (Windows): LogInit: Display: LogCook: Error: Content is missing from cook. Source package referenced an object in target package but the target package was marked NeverCook or is not cookable for the target platform.
UATHelper: Cooking (Windows):  Source package: /VRM4U/MaterialUtil/SampleMI/MI_VRM4U_Unlit
UATHelper: Cooking (Windows):  Target package: /Engine/EditorMeshes/ColorCalibrator/T_ColorGrid
UATHelper: Cooking (Windows):  Referenced object: /Engine/EditorMeshes/ColorCalibrator/T_ColorGrid.T_ColorGrid

**UnrealEngine Version:**
5.4.1 (compiled from source, NO modifications)

**Additional context**
Complete new project, ThirdPerson example. C++ project.
Plugin-> VRM4U_5_4_20240530 (latest)
Plugin saved directly on Project->Plugins -----(not on Engine)----

**By the way: congratulations for your work! =D Your plugin is awesome. Thanks man!**

**Comment by NightmareN-YT** [comment]
Hi! I'm new to this. where is the 'latest' folder?
