### ISSUE TITLE
ポーズアセットの問題

### ISSUE THREAD

**Issue by test222222222222** [ruyo/VRM4U#383]
Describe the bug
ポーズアセットのEyeblinkLeft等を動かしても機能しない物がいくつかある

Screenshots, log
![SnapCrab_NoName_2024-6-5_5-29-27_No-00](https://github.com/ruyo/VRM4U/assets/171577242/48582535-65ad-47b9-a42f-752437f0250a)

UnrealEngine Version:
ue5.4
VRM4U_5_4_20240530

**Comment by ruyo** [comment]
それらは、モデルにパーフェクトシンク対応のMorphTargetがある場合に動作します。
標準的なVRMでは、BlendShapeGroup（BlinkとかFun）の項目のみが動作するようになっています。
このへん詳しい解説がなくて申し訳ないです…

**Comment by test222222222222** [comment]
そうなんですね、わかりました。
ありがとうございます。
