### ISSUE TITLE
ランタイムロードの動作報告

### ISSUE THREAD

**Issue by monpoke8888** [ruyo/VRM4U#39]
こんばんは、UE４．２４で1.	パッケージ化してランタイムロードしたとき、MorphTargetが動作しない下記メッセージがでましたので情報共有いたします。
UE4.24のデバック画面の表情変更動作は問題ありませんでした。

またUE4.25はパッケージランタイムロードで下記のメッセージはでていないので
UEのバージョンチェンジで回避はできております。

Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/RenderCore/Private/RenderingThread.cpp] [Line: 853] 
Rendering thread exception:
Assertion failed: Index < (uint32)NumSplitsPerMorph.Num() [File:Runtime\Engine\Public\Rendering/MorphTargetVertexInfoBuffers.h] [Line: 73]

**Comment by ruyo** [comment]
すみません報告ありがとうございます。

こちらでも問題を確認し、修正しました。
エディタでは動いているので、最新ソースに更新すれば動作する状態にしてあります。

**Comment by monpoke8888** [comment]
ご連絡いただきありがとうございます。
修正を確認しました。
