### ISSUE TITLE
【VRM cannot implement physics correctly】vrmは物理を正しく実装できません

### ISSUE THREAD

**Issue by lizhimo** [ruyo/VRM4U#393]
In UE5 and UE4, rigid body physics cannot be achieved for hair or wing parts, but it can be displayed normally in Unity

こんにちは、ue 5とue 4のヘア物理または翼の部位ではリジッドボディ物理を実現できませんが、Unityでは正常に表示できます

https://github.com/ruyo/VRM4U/assets/170388546/a5369131-78b1-4f85-b297-cc491276bc85

**Comment by ruyo** [comment]
Hi.
The settings made by PhysicsAssest are simplified. It cannot reproduce the swing correctly.
The swing bones need to use VRMSpringBone.
When imported with the latest VRM4U plug-in, the VRMSpringBone is set by PostAnimBP.
You can check with this.

**Comment by lizhimo** [comment]
![1](https://github.com/ruyo/VRM4U/assets/170388546/dcaf7cc9-4111-44fd-bfe3-614200de337f)
![2](https://github.com/ruyo/VRM4U/assets/170388546/62b4e360-24c8-47c1-8941-0e05fc59e6bf)
![3](https://github.com/ruyo/VRM4U/assets/170388546/129341bb-b737-4485-ba76-6b79bb196c56)
![99c43e936ee2d42c00ad0bc59d1b4acf](https://github.com/ruyo/VRM4U/assets/170388546/b550d930-9afb-4e38-89fe-8f6feb4868f8)
I am using the latest version of VRM4U and I am not sure if the settings are correct. Some VRMs can be displayed normally and have good results, and I am not sure if it is a problem with the VRM file. However, these contents can be displayed correctly on Unity. Half of the bones cannot be physically displayed properly, and half of the physical display is rigid. The selected content is content that cannot be correctly swung. I provide the VRM file with the problem as follows

issues paper：https://drive.google.com/file/d/1EdMITWhwObveN1uqiMqNmQEZYjiOvfR2/view?usp=sharing

**Comment by ruyo** [comment]
Hi.
Thanks for the data.
This model has a branching bone specified for SpringBone.
This is not a recommended configuration, so I suggest you modify the VRM model.
Just to be sure, I will verify that it works the same way as in Unity.
<img width="1337" alt="image" src="https://github.com/ruyo/VRM4U/assets/6472835/1536fc23-6604-4be9-9695-03fc5350281f">

**Comment by lizhimo** [comment]
Thank you, separate binding can indeed solve the above problem
