### ISSUE TITLE
BP-PoseCopyToon character shadows and exposure issues

### ISSUE THREAD

**Issue by lizhimo** [ruyo/VRM4U#397]
Hello, BP PoseCopyToon is running in a level and character shadows cannot be displayed correctly. There are also issues with the display of images rendered by the sequence generator. If it doesn't run, everything will be fine in the view

The green pointer indicates normal
![1](https://github.com/ruyo/VRM4U/assets/170388546/ee9868d8-791d-49d7-b187-2e22c13810b7)
![2](https://github.com/ruyo/VRM4U/assets/170388546/d159762a-2230-461e-8cd2-1d8d0b6526aa)
![3](https://github.com/ruyo/VRM4U/assets/170388546/515a4c4f-a5a7-4a13-8702-629984acc90f)
![4](https://github.com/ruyo/VRM4U/assets/170388546/301cc584-eb3c-4d85-8331-de59fd0d5a1a)

**Comment by ruyo** [comment]
Hi.
BP_PoseCopyToon needs to adjust the lights.
Please refer to the documentation and use the debug display to adjust.

<img width="1920" alt="image" src="https://github.com/ruyo/VRM4U/assets/6472835/3c7987bd-6f7d-47de-b4c6-e7f18aa494c2">
<img width="1920" alt="image" src="https://github.com/ruyo/VRM4U/assets/6472835/35829bf7-7863-40d2-b686-9c825f0c36ca">

**Comment by lizhimo** [comment]
こんにちは、私の表現はよくわかりません。申し訳ありませんが、以下は私の問題です
Hello, I didn't express myself very clearly. Sorry, the following is my question

https://github.com/ruyo/VRM4U/assets/170388546/28aff0a4-7419-4822-a8e0-14bd35943e1f

**Comment by ruyo** [comment]
Have you checked the debugging view?
Perhaps the settings are shifted during PlayIn. I'll try to change the initialization method, so please try it in the next release.

**Comment by lizhimo** [comment]
I have searched and currently found no solution. I am eagerly anticipating the next version update.
