### ISSUE TITLE
パッケージ化したexeが開かない

### ISSUE THREAD

**Issue by tuyurin583** [ruyo/VRM4U#400]
環境:
Windows
UE5.4(VRMも5.4のもの)を使用
Pluguins>VRM4U>Content>Util>Actor>latestのみ削除

サードパーソンテンプレートでプロジェクト作成後パッケージ化を行いexeファイルを開こうとしましたがexeが開きません

**Comment by ruyo** [comment]
パッケージ化まで成功しているのであれば、VRM4Uの問題ではなさそうな気配がします。
試しにですが、以下を確認してみてください。
・VRM4Uを導入していないプロジェクトのexeが起動するか
・VRM4Uを導入後、VRMインポートを行っていないプロジェクトのexeが起動するか

また、おそらくユーザーフォルダのどこか(たぶんAppData\Local)にログファイルが出力されていると思いますので、内容に問題なければ添付をお願いします。

**Comment by hiroshibtc** [comment]
ruyoさん
違う件かもしれませんが、同様の症状のため、こちらに自分が検証した内容含めてまとめておきます。
解決の手がかりになる情報があれば幸いです。

【環境】
Win11
UE5.4.2
VRM4U 20240606/20240617/20240516（３バージョンで試しました）

【検証した内容】
１．デフォルトのThirdpersonテンプレート
２．VRM4Uをプロジェクトのpluginsフォルダにいれて再起動
３．VRM4Uを使ってVroidのキャラをMtoonUnlit の初期設定でインポートする
４．インポートしたskeletalmeshをレベルに配置する

すべてパッケージ化は成功しますが、1以外は起動しません。
また、一度2移行まで進めたプロジェクトからVRM4Uのプラグインを無効化してパッケージ化すると起動できるようになります。

念のためUE5.4.2を再インストールしましたが、同じ結果でした。

**Comment by tuyurin583** [comment]
・VRM4U を導入していないプロジェクトのexeが起動するか→起動しました
・VRM4U を導入後、VRMImport を行っていないプロジェクトのexeが起動するか→起動しませんでした
Appdata/Local/プロジェクト名/Saved/Logには何も入っていませんでした
〃/Saved/Config/CrashReportClient/CrashReportClient.iniがあったので添付します。
[CrashReportClient.txt](https://github.com/user-attachments/files/16162255/CrashReportClient.txt)

**Comment by tuyurin583** [comment]
Editor Scripting Utilities プラグインを無効にすることで無事パッケージ化後exeファイルを開けるようになりました

**Comment by syui** [comment]
この現象は`vrm4u 20241002`にすると発生し始めました。 ue 5.4.4, ue 5.5.0p

Editor Scripting Utilities プラグインを無効にすると開けるようになります。

また、Editor Scripting Utilities プラグインが有効でも`20240823`に上書きすると開けます。
