### ISSUE TITLE
"Retarget Animation Assets > Duplicate and Retarget Animation Blueprint" option is missing

### ISSUE THREAD

**Issue by tanakawatanabe** [ruyo/VRM4U#405]
I retargeted my VRM model by using IK retargeter.
![スクリーンショット 2024-08-01 041708](https://github.com/user-attachments/assets/2e258064-d699-45a6-8625-ca459e27f40d)
I followed this tutorial.
https://ruyo.github.io/VRM4U/03_gray/#%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E3%81%A7%E3%83%AA%E3%82%BF%E3%83%BC%E3%82%B2%E3%83%83%E3%83%88%E3%81%99%E3%82%8Bue5%E6%A8%99%E6%BA%96%E6%A9%9F%E8%83%BD
I set Source IKRig to IK_Mannequin, set Target IKRig to my IKRig generated by VRM4U import.
And I opened WBP_Retarget, set Retargeter and Source Pose and hit Update IKRetargeterPose.
![スクリーンショット 2024-08-01 041758](https://github.com/user-attachments/assets/cbeb2563-68fa-48ff-a7c3-59ad4e6efbb8)
It didn't make my VRM to A-pose, so I googled and found this tweet and followed procedure.
https://x.com/se_zu06re/status/1649696718370512896
After that, VRM became A-pose and looks like retargeting worked fine.
![スクリーンショット 2024-08-01 041921](https://github.com/user-attachments/assets/5c92bca8-1e38-4957-a58f-aafd04d48a0c)

The problem is, when I try to retarget ABP for my VRM,
The option "Retarget Animation Assets > Duplicate and Retarget Animation Blueprint" is missing.
![スクリーンショット 2024-08-01 042028](https://github.com/user-attachments/assets/3d2e5027-ea9a-4247-a8f2-71ff7e625b3f)

What am I missing?
My UE version is 5.4.3-34507850+++UE5+Release-5.4.
Downloaded VRM4U is VRM4U_5_4_20240728.

**Comment by ruyo** [comment]
Hi.
This is not a VRM4U problem.
Try the following in the editor.

<img width="1562" alt="image" src="https://github.com/user-attachments/assets/42569d72-1ed6-41d9-93f0-646472282882">
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/83500c2b-f818-4a26-a973-daa70d86874f">

**Comment by tanakawatanabe** [comment]
Thanks.
I followed the procedure and now ABP's got retargeted.
So I tried to replace gray man NPC with my VRM, by changing Skeletal Mesh Asset and Anim Class.
It looked working well in the viewport.
![スクリーンショット 2024-08-04 014002](https://github.com/user-attachments/assets/cd79bf08-ddd3-4e00-83d0-a1e56b43afce)

But in the scene view in edit mode it's completely messed up.
![スクリーンショット 2024-08-04 013647](https://github.com/user-attachments/assets/0a28db94-edfa-4574-958d-39bdf37e65d3)

When I hit Play they move like this:
https://vimeo.com/994560962?share=copy

This is how the original gray man NPCs were moving:
https://vimeo.com/994561737?share=copy

Any idea what's goin on?

And one more question.
Firstly I was horrified having ABP copies for each character models,
thinking adding and editing something (like cover system or car interaction etc.) for each ABPs.
And I found a tweet you mentioning "retargeting preserves parent and child structure of ABP":
https://x.com/ruyo_h/status/1515381454452445186
I carelessly jumped to conclusion like,
"Oh so if I edit or add something in original ABP, it applies all copied ABPs? Like prefab variant in Unity? Nice!"
But it doesn't happen, am I right?

**Comment by ruyo** [comment]
Perhaps it is a problem with AnimBlueprint itself. Some parameter is probably affected. I cannot support this in detail.
If you do not know the cause of the problem, I recommend that you try to create an AnimBlueprint from scratch once.

That post explains the relationship between ABP_Manny and ABP_Quinn.
If you want to know more about animation sharing, I suggest you search for the ABP inheritance relationship and Skeleton sharing.
GameAnimationSample is also a good reference if you want to know the latest mechanism using IKRetargeter.

**Comment by tanakawatanabe** [comment]
I watched some tutorials about ABP child inheritance,
but child ABP is generated by "Create Child Animation Blueprint" option, and also stuck on the same skeleton of parent.
In my case the new ABP for VRM is generated by "Retarget Animations" menu,
and the new ABP has no child-parent relationship to original ABP. So it doesn't help.

I installed GameAnimationSample, and put VRM4U in it,
imported my VRM, and tried to retarget from UEFN Mannequin, referencing this tutorial:
https://youtu.be/G16L3-sSwG4?si=dEhwZu7wDbXo2pWo&t=623
To "Export Retarget Assets" I had to check in "Auto Generate Retargeter",
but it ended up unmatching result.
![スクリーンショット 2024-08-06 020845](https://github.com/user-attachments/assets/d1f0b810-b7be-4c48-a8c7-6cb4d41725f7)

I know this is probably impossible and ridiculous but,
it would be really great if this real time retargeting method can be used in the edit mode:
https://ruyo.github.io/VRM4U/03_gray/#%E3%83%AA%E3%82%A2%E3%83%AB%E3%82%BF%E3%82%A4%E3%83%A0%E3%83%AA%E3%82%BF%E3%83%BC%E3%82%B2%E3%83%83%E3%83%88%E3%81%99%E3%82%8Bvrm4u%E3%81%AE%E6%A9%9F%E8%83%BD
This method is so easy in case just to replace gray man to VRM in play mode,
but in the edit mode all characters are gray man, so if I set rifle on grayman's hand properly,
it flies away when the model is retageted to VRM in the play mode.
And thinking about making cutscenes using Sequencer in edit mode,
posing and adjusting everything in edit mode with grayman, imaging it will be replaced with VRM,
I think this InPlay retargeting won't fit in my actual development.
Is it really impossible to use real time retargeting method in edit mode?

**Comment by ruyo** [comment]
I think what you want to do is included in the GameAnimation sample.

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/f542ffc9-56e3-43c2-88b1-8c3dda4c5042">

**Comment by tanakawatanabe** [comment]
OK, now I understand retargeted models can share the same ABP,
but how did you retarget that girl?

This time I followed this tutorial:
https://youtu.be/qthWtNCk1RQ?si=BBy8Kho3huSiwl77&t=124

I copied IK_ and RTG_ and named it _MobMiko.

In IK_MobMiko_Retarget, I changed Preview mesh to MobMiko and this is what I got:
![スクリーンショット 2024-08-07 062213](https://github.com/user-attachments/assets/1ee00287-abc2-4208-9ebb-7e962a3c54f6)
Looks like log saying VRM is missing some bones (like "foot_l" and "foot_r", etc).

And in RTG_UEFN_to_MobMiko, I followed procedure retargeting VRM manual:
https://ruyo.github.io/VRM4U/03_gray/#%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E3%81%A7%E3%83%AA%E3%82%BF%E3%83%BC%E3%82%B2%E3%83%83%E3%83%88%E3%81%99%E3%82%8Bue5%E6%A8%99%E6%BA%96%E6%A9%9F%E8%83%BD
But it didn't go well. VRM is stuck in A-POSE.
![スクリーンショット 2024-08-07 062811](https://github.com/user-attachments/assets/ee8f5810-6922-4fc2-b3a2-7ec4b362dedb)

Just in case I copied and made MobMiko character BP and added to list, but it ended up in T-pose.
![スクリーンショット 2024-08-07 064207](https://github.com/user-attachments/assets/fb468b6c-696b-4d63-9743-6be6467635f3)

So I thought this is because IK_MobMiko_Retarget is giving some errors saying missing bodyparrts,
I added chain and tried to assign pelvis bone, but UE won't let it assign.
https://vimeo.com/995566896?share=copy

How did you get IK Rig made by VRM work properly?

**Comment by ruyo** [comment]
In the GameAnimation project
Importing VRM generates an IKRetargeter named RTG_UEFN_vrmfilename.
Please use this as it is, no operation with WBP is required.

**Comment by tanakawatanabe** [comment]
Thx, now the RTG looks fine.
![スクリーンショット 2024-08-10 062235](https://github.com/user-attachments/assets/2497ab27-d0ba-493c-8bc4-a0cf3e3af1bd)

So the last part is making CharacterBP variant.
![スクリーンショット 2024-08-10 062554](https://github.com/user-attachments/assets/a75c5699-b7c3-414a-8f9c-8a9eaa2aadbc)
I looked other inherited CharaBP using different SkeltalMesh,
it was just changing child's Skeletal Mesh Asset to original one.
![スクリーンショット 2024-08-10 062554](https://github.com/user-attachments/assets/4a89d839-aa8a-4d65-aec0-3b8d67a2fb2c)

So I thought it's quite easy and edited my VRM's BP(inheriting "CBP_SandboxCharacter_AllCharacters"),
changed Skeletal Mesh Asset to my VRM.
![スクリーンショット 2024-08-10 062734](https://github.com/user-attachments/assets/1d88fabb-c158-4f6a-9056-1d9234b7375e)
But it ended up in T-pose same as before.
I think there should be somewhere to connect RTG in Details menu in CharaBP,
but I could find it. Where is it?

**Comment by ruyo** [comment]
Please refer to the official documentation on how to replace characters in the GameAnimation sample.

https://dev.epicgames.com/documentation/en-us/unreal-engine/game-animation-sample-project-in-unreal-engine#implementyourcharacter

**Comment by tanakawatanabe** [comment]
![スクリーンショット 2024-08-15 223425](https://github.com/user-attachments/assets/6dd19964-a07c-4cec-bf9d-f7dfb4f5f424)

Thanks! Finally I made my VRM to work with ABP_GenericRetarget!

**Comment by tanakawatanabe** [comment]
Thx for your support I managed to use my VRM to work with generic ABP.

There's one more thing I'm wondering: Can I share UEFN skel animations with VRM in Sequencer?
I put CBP_SandboxCharacter(UEFN) and assigned running animation(UEFN) in Sequencer,
and of course it animates as expected.
Next, I put CBP_SandboxCharacter_Mehera_Lite(from VRM, child blue print of CBP_SandboxCharacter,
 works fine with generic ABP in play mode) in Sequence,
tried to copy UEFN run animation to VRM's track, but it was refused.
![スクリーンショット 2024-09-02 004141](https://github.com/user-attachments/assets/ff74819b-f614-4a6c-bf7c-4c0fc9a99aee)

Looks like this retargeting method is also only available in play mode.

Many of articles recommend to use IK retargetter and export retargeted animation files,
but that's last thing I want to do. If I make a cutscene where 4 VRM characters running same animation from UEFN fbx,
do I have to create 4 retargeted ABPs and Animation Sequences for each VRM?

**Comment by ruyo** [comment]
The model is working by retargeting the UEFN mannequin.
Therefore, animations must be set for the UEFN mannequin.

Questions that have nothing to do with VRM4U, I think you will get more accurate answers using the Forum.  

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/df973578-5e05-4181-9749-ef1558613bb5">

**Comment by ruyo** [comment]
Check optimization settings.
<img width="1242" alt="image" src="https://github.com/user-attachments/assets/c66ba7ee-e8fb-4034-bc97-c8b39bc63fe8">

**Comment by tanakawatanabe** [comment]
That's it! Now it's working!
Thanks for everything!
