### ISSUE TITLE
The facial expression of vmc does not move after build

### ISSUE THREAD

**Issue by syui** [ruyo/VRM4U#408]
It works fine in the editor, but after building it, the facial expressions stop working. Only the facial expressions don't work, everything else works.

- ue 5.4.3
- third person template
- vrm4u 20240728
- vrm 0.x(no-option)

---
## [ja]build後にvmcの表情が変化しない
editorでは問題なく動くのですが、build後に表情が動かなくなってしまいます。動かないのは表情のみで他は動きます。

**Comment by ruyo** [comment]
Hi.
Please use the latest version.
Release binaries have been updated.

**Comment by syui** [comment]
thx, great!

**Comment by syui** [comment]
`vrm4u 20240823`にupdateしてみました。
再度buildしてみましたが、表情は動きませんでした。

third person templateの環境ではvrmとpluginを削除して再度インポートしてみました。不思議なことにeditor上でも表情が動かなくなってしまいました。

**Comment by syui** [comment]
その後、古いバージョンをもう一度同じthird person template環境で試してみたところ、third person template環境ではもともと表情が動いていなかった可能性が出てきました。

表情って動くものなのでしょうか?以下は少し特殊なABPからvrm4u(vmc)を読み込んでいます。

https://github.com/user-attachments/assets/72524991-46b4-46dc-acee-b76cb3cb36c4

**Comment by ruyo** [comment]
VRM4U_runtimeload を初期マップにしてPKGを作成し、起動してみてください。
このマップでは ランタイムロードとランタイムリターゲット、フェイシャル のテストができます。
周期的に 目を閉じる処理が入っていますので 参考にしてみてください

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/41578379-8a0f-49bb-9f94-351eb0f21ad9">

**Comment by syui** [comment]
原因がおそらく判明しました。ABPのAnimGraphは`VRM4U Pose(Audo Search) -> Output Pose`で終了しなければなりません。

**Comment by syui** [comment]
editor上ではこれで動くようになりましたが、build後はやはり動きませんでした。

**Comment by syui** [comment]
この問題はlivelinkのpresetsで解決できるようです。
https://github.com/ruyo/VRM4U/issues/422#issuecomment-2366727682
