### ISSUE TITLE
UE5.4 Modular Rig Control weird legs

### ISSUE THREAD

**Issue by ManaHime** [ruyo/VRM4U#411]
When using the new 5.4 modular control rig (animation → control rig → modular control rig) the only skeleton that can be used by default seems to be the ue4mannequin. But, when using the leg module, the legs became weird.

UE5.4の新しい「Modular Control Rig」（Animation → Control Rig → Modular Control Rig）を使用する際、使えるスケルトンはUE4マネキンだけです。でも、Leg Moduleを使うと、脚は変になります。

こんな感じかな：
![image](https://github.com/user-attachments/assets/c5a8ae9c-f69f-4733-9b92-22ce237c4175)

**Comment by ruyo** [comment]
Hi.
The standard ModulerRig cannot be used. This is because the bone orientation is different.
At this time, it is difficult to create a ModulerRig for various VRM models.

**Comment by ManaHime** [comment]
That makes sense!
I read the documentation, and I now understand that there is a utility to create control rigs.
Thank you very much for your hard work!
