### ISSUE TITLE
Not clear how to use plugin in different unreal versions

### ISSUE THREAD

**Issue by Volcanicus** [ruyo/VRM4U#418]
I have your plugin from since 4.27 and that one works fine.
I came back recently to try to use it in 5.1 or 5.3 but it seems it only works on 5.4
There are way too many updates to keep track of. Could you somehow make either branches to the other versions or do you have a link for them?
Thank you!

**Comment by ManaHime** [comment]
Can you explain what you mean?
Each supported version of Unreal Engine have their own build.
Do you get issues if you download the release for the version of Unreal Engine that you want?
For example, do you get an error if you try to use the following with UE5.1?
https://github.com/ruyo/VRM4U/releases/download/20240823/VRM4U_5_1_20240823.zip

**Comment by Volcanicus** [comment]
I found what you mean and it was difficult to find.
https://github.com/ruyo/VRM4U/releases
This is the link.
