### ISSUE TITLE
Missing precompiled manifest for launch  error 

### ISSUE THREAD

**Issue by Gekinzen** [ruyo/VRM4U#42]
when im trying to launch or  package the project I encountered error message please see below  thanks ! 

LogPlayLevel: Error:   ERROR: Missing precompiled manifest for 'Launch'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in Launch.build.cs to override.

**Comment by ruyo** [comment]
Hi.

Perhaps it's an error in another plugin or source. VRM4U does not use the 'Launch' module.
Try testing your build with a simple project.

**Comment by Gekinzen** [comment]
Yes I already saw the problem :) Thanks !
