### ISSUE TITLE
VMC is not working in 5.5

### ISSUE THREAD

**Issue by iJzFan** [ruyo/VRM4U#426]
**Describe the bug**
Can not receive vmc data.

**Screenshots, log**
![QQ20241014-012154](https://github.com/user-attachments/assets/d29b5dd4-8a2e-4e5a-99a5-cc7806ec6736)

**UnrealEngine Version:**
UE5.5 preview1

**Comment by iJzFan** [comment]
From my tests, 5.5 doesn't work with ip 127.0.0.1 and the editor doesn't get update like 5.4 before.

**Comment by ruyo** [comment]
Hi. See here.
I will update the sample in the next release.
https://ruyo-github-io.translate.goog/VRM4U/08_vmc/?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja

Thanks
