### ISSUE TITLE
When I Imported PMX file, I try redirect animation from my animation, but failed

### ISSUE THREAD

**Issue by noobGuaTai** [ruyo/VRM4U#431]
The prompt is attempting to automatically generate a redirect, but there is no template compatible with the target mesh
and Root bone motion remapping operation, missing target pelvic bone None.
Then I try use Modular Rig to animate, but no matter what i darp any bone in the first socket , there is no new socket appeared.
![image](https://github.com/user-attachments/assets/66bda99b-15e2-41b5-a9be-edef9261d478)

**Comment by ruyo** [comment]
Hi.
VRM4U automatically generates a retargeter with the mannequin. Please use it.
Modular Rig is only compatible with EpicSkeleton.

**Comment by noobGuaTai** [comment]
very thanks!I found I can set all redirection link manually.
