### ISSUE TITLE
VRM Spring Bone animations worked in the Editor, but not in the cooked build; Had to manually assign Vrm Meta Object reference to fix

### ISSUE THREAD

**Issue by andreiagmu** [ruyo/VRM4U#435]
Unreal Engine v5.4.4
VRM4U v20241007

**Describe the bug**
I had an issue where the VRM Spring Bone animations worked in the Editor, but not in the cooked build.
Turns out I needed to explicitly assign the `Vrm Meta Object` reference, in my character's `ABP_Post` animation blueprint.

![capture_20241105_191602_014_edit](https://github.com/user-attachments/assets/f353fa82-8cb9-4995-8344-8fe0212d4767)

![capture_20241105_191643_015_edit](https://github.com/user-attachments/assets/8a6f6f3b-941a-4765-92c3-c701a121d96e)

Inside `ABP_Post`, there are a few nodes that have the `Enable Auto Search Meta Data` property.
But it seems this property only works in the Editor.

![capture_20241105_191721_016_edit](https://github.com/user-attachments/assets/d18a9e7d-12d4-42dc-a440-1e5ef8437c95)

![capture_20241105_191748_017_edit](https://github.com/user-attachments/assets/3dac0023-8e09-443f-be47-3fbfc7518a94)

Ideally, the `Vrm Meta Object` reference should be already assigned when importing the character.
Or, the `Enable Auto Search Meta Data` logic should be improved, to also work in the cooked build.

**Comment by ruyo** [comment]
Hi.
I think the reason is that vrmassetList is not a cook target.
Please check it in the reference viewer and make sure it is referenced by the assets to be Cooked.
AutoSearch itself is working correctly after the cook.

**Comment by andreiagmu** [comment]
Note: My avatar is dynamically spawned in the map via a custom BP, which is set as my `Default Pawn Class` in my `Game Mode` BP.

After checking the Reference Viewer, it seems that when I don't add the explicit VrmMeta reference to ABP_Post, the _only_ thing referencing VrmMeta is the VrmAssetList. The VrmAssetList is, in turn, referenced by the VrmMeta _only_.

But after I add the explicit VrmMeta reference to ABP_Post, _then_ the VrmMeta is referenced by the ABP_Post, which is in turn referenced by:
`the avatar's Skeletal Mesh -> my custom Default Pawn Class BP -> Game Mode BP`

Note: In my project, I use the `List of maps to include in a packaged build` setting from `Project Settings -> Project -> Packaging`, to avoid cooking unused/unneeded assets.
Maybe this is also affecting the VrmMeta/VrmAssetList references somehow.

**Comment by andreiagmu** [comment]
Fixed in release [20241110](https://github.com/ruyo/VRM4U/releases/tag/20241110).
Thanks!

**Comment by Reaper1103** [comment]
Hello, I've encountered this problem too. I'm using the latest version, but when I make the Vrm Meta Object into a variable, the animation fails to work during runtime. Could you tell me if there is something wrong with my settings?
