### ISSUE TITLE
In Linux systems, file names are case sensitive, resulting in errors

### ISSUE THREAD

**Issue by MacroGu** [ruyo/VRM4U#443]
**Describe the bug**
can not compile under linux

https://github.com/ruyo/VRM4U/pull/433

**Screenshots, log**
In Linux systems, file names are case sensitive, resulting in errors

**UnrealEngine Version:**
UE5.4.4

**Additional context**
Source/VRM4U/Public/VrmBPFunctionLibrary.h
#include "AssetRegistry/Assetdata.h"
#include "AssetRegistry/AssetData.h"

[https://github.com/ruyo/VRM4U/pull/433](url)

**Comment by ruyo** [comment]
Thanks! I merged it.
