### ISSUE TITLE
cannot package project

### ISSUE THREAD

**Issue by Xi-v** [ruyo/VRM4U#45]
![image](https://user-images.githubusercontent.com/72281205/96997758-0b31d100-153b-11eb-8f1f-d20c4df4a7ec.png)

**Comment by ruyo** [comment]
Hi.

I don't know what you're doing, but if you have a log or screenshot, I'll look it up.
VRM4U has Content in the plugin. You need to enable the plugin to see them.

**Comment by Xi-v** [comment]
![image](https://user-images.githubusercontent.com/72281205/96997758-0b31d100-153b-11eb-8f1f-d20c4df4a7ec.png)

**Comment by ruyo** [comment]
Thank you for information.

There seem to be several reasons. Please check in the following order.

1.
Is VisualStudio2019 installed?
Please also check the installation options from the following page.
https://docs.unrealengine.com/en-US/Programming/Development/VisualStudioSetup/index.html

2.
Is it a CPP project?
From the following page, add a dummy C++ class and change it to a CPP project.
https://docs.unrealengine.com/en-US/Programming/QuickStart/2/index.html

**Comment by Xi-v** [comment]
thanks, i find what need i do and now its working.

**Comment by markuslement** [comment]
> thanks, i find what need i do and now its working.

Tell me how you solved this problem?
