### ISSUE TITLE
when using vrm1, the model's bangs float up

### ISSUE THREAD

**Issue by syui** [ruyo/VRM4U#451]
## version

- unrealengine 5.5.0
- vrm4u [20241113](https://github.com/ruyo/VRM4U/releases/tag/20241113)
- vrm-1.0

When using vrm1, the model's bangs will lift up. This is due to the `collision` of `VrmSpringBone`.

may depend on the model you are using, but perhaps you should change the default value?

![スクリーンショット 2024-11-20 170900](https://github.com/user-attachments/assets/27adb47b-189b-4561-a2c5-1c2ea7f97b5b)

Changing the value as below will fix the issue:

> VM_${name}_VrmMeta

```json
[
  [
    {
      "bone Name": "J_Sec_Hair1_03",
      "Hit Radius": 0
    },
    {
      "bone Name": "J_Sec_Hair2_03",
      "Hit Radius": 0.01
    },
    {
      "bone Name": "J_Sec_Hair3_03",
      "Hit Radius": 0.01
    }
  ],
  [
    {
      "bone Name": "J_Sec_Hair1_04",
      "Hit Radius": 0
    },
    {
      "bone Name": "J_Sec_Hair2_04",
      "Hit Radius": 0.01
    },
    {
      "bone Name": "J_Sec_Hair3_04",
      "Hit Radius": 0.01
    }
  ],
  [
    {
      "bone Name": "J_Sec_Hair1_05",
      "Hit Radius": 0
    },
    {
      "bone Name": "J_Sec_Hair2_05",
      "Hit Radius": 0.01
    },
    {
      "bone Name": "J_Sec_Hair3_05",
      "Hit Radius": 0.01
    }
  ]
]
```

## fix version

![スクリーンショット 2024-11-20 170920](https://github.com/user-attachments/assets/ac31bb83-d959-4bd8-8502-203b136b5cf1)

[ja-jp]
vrm1を使用するとモデルの前髪が浮き上がってしまいます。これは`VrmSpringBone`の`collision`によるものです。
使用するモデルによるかもしれませんが、デフォルトの値を変更したほうがいい可能性はありますか?

**Comment by ruyo** [comment]
From that debugging display, I think the version of the plugin is out of date.
Please check the behavior by using the latest first.
