### ISSUE TITLE
WBP VRMMaterialのMtoonActorアクションの問題

### ISSUE THREAD

**Issue by xizro345** [ruyo/VRM4U#464]
**Describe the bug**

WBP VRMMaterialの最新バージョンで、MtoonActorアクションに「ToggleAttachMtoonActor」と「ToggleOutlineComponent」が追加されていることに気付きました。
リリースノートには記載がありませんでしたが、「ToggleOutlineComponent」はアウトラインのみを必要とする場合のオプションでしょうか？ それとも「AttachMToonActor」と併用する必要がありますか？
また、VRM4Uの最新バージョン（12月27日リリース）では、アウトラインが機能しないようです（「ToggleAttachMtoonActor」と「ToggleOutlineComponent」の両方でテストしました）。
以前のVRM4Uバージョンでは正常にアウトラインが表示されていました。
モデルは、以前のVRM4UバージョンでインポートされたVRM1.0です。

**Screenshots, log**
![immagine](https://github.com/user-attachments/assets/dc8dac78-22a5-45ef-a4dd-335679e39fc1)

![immagine](https://github.com/user-attachments/assets/d2853777-732f-4ef7-8e25-5820fc1e1cf5)

**UnrealEngine Version:**
UE 5.4.4

**Additional context**
VRM4U 20241227

**Comment by ruyo** [comment]
すみません、不具合のせいで挙動がわかりにくくなっています…

・最新にてアウトラインが出なくなっている
不具合です。次回リリースで修正されます。

・MToonActor、OutlineComponentの動作
MToonActorの動作に変更ありません。従来どおり、単体でアウトラインが表示されます。
新機能として、アウトラインのみを利用したい場合は OutlineComponent を利用することができます。

・Widgetの動作
WidgetからはMToonActor と OutlineComponent それぞれをON/OFF トグルできるようになっています。
操作上、両方を同時に有効化できますが、併用する必要はありません。

**Comment by xizro345** [comment]
投稿した画像は、どちらのオプションもアウトラインに影響しなかったことを示すためのものです。
バグとのことなので、次回のリリースを待ちます。
ご対応ありがとうございます。

**Comment by xizro345** [comment]
投稿した画像は、どちらのオプションもアウトラインに影響しなかったことを示すためのものです。
バグとのことなので、次回のリリースを待ちます。
ご対応ありがとうございます。
