### ISSUE TITLE
Cant package  the game so frustate UE 4.20

### ISSUE THREAD

**Issue by zheroisland** [ruyo/VRM4U#50]
Everytime I package the game using VRM plugin always error.

I tried to create new project and then package without VRM plugin I have no issue, but when I package with VRM package will error.
1. I downloaded the plugin in here https://github.com/ruyo/VRM4U/releases/tag/20200625

I choose VRM4U_4_20_20200625.zip , downloaded , extract, then I copy folder "plugins" to my game folder project

2. I Click and drag VRM file inside editor and put it on map

3. Package the game

Here I provide Video for error to make it clear 
https://youtu.be/XXI6Pjddoqk

Also the log
[MyProject.log](https://github.com/ruyo/VRM4U/files/5766732/MyProject.log)

Really appreciate if you can provide video tutorial how to fix it. I really need help @ruyo

**Comment by zheroisland** [comment]
Ruyo cant fixed the issue, so I delete his plugin. No need anymore. thanks

**Comment by zheroisland** [comment]
!

**Comment by ruyo** [comment]
I'm really sorry I didn't notice your post.

You need to get the VRM4U source and extract it as shown in the link below.
If you have a chance to use it again in the future, please refer to it.

https://d3etapyazx4hzgaanfq2hik3j4--ruyo-github-io.translate.goog/VRM4U/03_exe/
