### ISSUE TITLE
Unknown build error (UE 4.26)

### ISSUE THREAD

**Issue by jinhyung2003** [ruyo/VRM4U#52]
I'm currently having issue pakaging the game with VRM4U. I've already checked that I'm using the one with pakaging (liked with EpicGames) and VRM4UEditor type is set to "Editor." Just a quick  look to the log, it seems that URM4ULoader is having trouble to be packaged:

UATHelper: Packaging (Windows (64-bit)):     C:/Users/jinhy/Desktop/Project_FUSION/Plugins/VRM4U/Source/VRM4ULoader/Private/VrmConvert.cpp(30): warning C4996: 'CreatePackage': Use CreatePackage overload that does not take the first Outer parameter. Specifying non-null outers for UPackages is no longer supported. Please update your code to the new API before 
upgrading to the next release, otherwise your project will no longer compile.

[log.txt](https://github.com/ruyo/VRM4U/files/5824361/log.txt)

**Comment by ruyo** [comment]
Thanks for the info.
I do see the warning on the VRM4U side. I will fix this one.
However, from the logs, it seems that the direct cause of the packaging error is due to the format of 'Application.ico'.
Can you try to modify the icon file and see if you can package it?

**Comment by jinhyung2003** [comment]
Thanks for the issue.
I changed the ico file, but now this shows up:

UATHelper: Packaging (Windows (64-bit)):   LogInit: Display: LogBlueprint: Error: [AssetLog] C:\Users\jinhy\Desktop\Project_FUSION\Plugins\VRM4U\Content\Util\Actor\latest\WBP_ControlRig.uasset: [Compiler] In use pin  Dst Control Rig BP  no longer exists on node  Get . Please refresh node or break links to remove pin. from Source: /VRM4U/Util/Actor/latest/WBP
_ControlRig.WBP_ControlRig

I'm still having issue pakaging the plugin...

**Comment by ruyo** [comment]
I see. Please delete the following directory.

/VRM4U/Util/Actor/latest/

This is where you will find experimental tracking and ControlRig data. It is not needed for packaging, so you can delete it.
I'll think of a way to fix it...

**Comment by jinhyung2003** [comment]
Thanks for helping out! It finally works.
