### ISSUE TITLE
Cant Package

### ISSUE THREAD

**Issue by DropDeadBlinko** [ruyo/VRM4U#53]
Hey,

wanted to say great work with the plugin, having a few issues,
I am using UE4.26.0 and your latest VRM4U_4_26_20210112,
I have extracted the zip file into the project plugins folder, 
I have tested in a new c++ project,
Importing vrm files works great, but when i try to package i keep getting the same errors;

UATHelper: Packaging (Windows (64-bit)):   WARNING: The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)

UATHelper: Packaging (Windows (64-bit)):   C:\Users\jblin\Documents\Unreal Projects\Battery_Collector\CConvert\Plugins\VRM4U\VRM4U.uplugin: warning: The 'Developer' module type has been deprecated in 4.24.

PackagingResults: Warning: The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)

PackagingResults: Warning: The 'Developer' module type has been deprecated in 4.24.

UATHelper: Packaging (Windows (64-bit)):   ERROR: Could not find definition for module 'VRM4U', (referenced via CConvert.uproject -> VRM4U.uplugin)

PackagingResults: Error: Could not find definition for module 'VRM4U', (referenced via CConvert.uproject -> VRM4U.uplugin)

Any suggestions?

thank you in advance :)

**Comment by ruyo** [comment]
Hi.
The VRM4U source files are required for packaging.
Please refer to the following page.
It also describes the 'UncookedOnly' warning.
https://d3etapyazx4hzgaanfq2hik3j4--ruyo-github-io.translate.goog/VRM4U/03_exe/

thanks

**Comment by DropDeadBlinko** [comment]
Thank you for your quick response
Not sure if you can help with this but i cant seem to access the source download link, i have linked my github account as it says, but i still get the 404 error message

**Comment by ruyo** [comment]
Can you see the Epic repository? If you get a 404 page, then your account is not properly connected.
As mentioned in the previous document, please check your email and follow the correct procedure.

https://github.com/EpicGames/UnrealEngine

**Comment by DropDeadBlinko** [comment]
Hey, sorry deleted the last message as i sorted the issue out, i believe it was an issue with my web browser, but i can access the repository now, it says to save in the "MyProject/Plugins/VRM4U/Source/" but I cant see the "Source" folder in my project folder

thanks again

**Comment by ruyo** [comment]
You can extract the contents of the source repository by overwriting it.
Perhaps it is a problem with automatic translation...

**Comment by DropDeadBlinko** [comment]
I think the problem was the project, not entirely sure why, but ive got it working with a different project, thank you for your help :)
