### ISSUE TITLE
Can't package game, files not found

### ISSUE THREAD

**Issue by Ezoriel-Zen** [ruyo/VRM4U#58]
Hi, i am getting warnings when i try to package the game to both Win64 and Android. Unreal engine can't find any files from VRM4U plugin and eventully it fails the packaging, i have no problems importing characters.

![warnings](https://user-images.githubusercontent.com/78830580/107662697-d634c000-6c8a-11eb-9f22-bf38bc63759c.png)

What i have done so far:

1. Added VRM4U plugin to ue4.26.1 plugin folder in engine (no source)
2. Created a new blueprint project with ue4.26.1
3. Added a c++ class to the project
4. Closed project and added VRM4U plugin to project plugin folder and then overwritten with source files
5. Tried to package game and it fails

Full log ([Nixxer.log](https://github.com/ruyo/VRM4U/files/5966859/Nixxer.log))

**Comment by ruyo** [comment]
Hi.
Thanks for attaching the log.
Delete the files in /VRM4U/Util/Actor/latest and try to create the package again.
You will find experimental assets such as HandTracking and ControlRig. In most cases, these are not needed for packaging.

Sorry for the confusing procedure. I have updated the documentation.

**Comment by Ezoriel-Zen** [comment]
Thanks for helping me ruyo, that fixed all my problems!
