### ISSUE TITLE
How to import animations in fbx to UAnimSequence with VRM4U?

### ISSUE THREAD

**Issue by hamkoo** [ruyo/VRM4U#7]
How to import animations in fbx to UAnimSequence with VRM4U?

**Comment by ruyo** [comment]
Hi.
It's a bit confusing.
Simply, please use 'epic skeleton' and retarget by UE4.
If you want to use original bone,
a model which has same bone as imported skeletal mesh is needed.
VRM4U remove some extra bones from original model.

Thanks!

**Comment by hamkoo** [comment]
Thanks for your reply.
I'll continue to find the way how to create an animSequence with c++.

**Comment by ruyo** [comment]
UAnimSequence is made with VrmConvertModel.cpp from '.glb' file. Please try to reference.
Thanks!

**Comment by hamkoo** [comment]
I've got the problem while creating an animsequence to a package.
In ue4 engine, the function will been called:

> bool CompressRawAnimSequenceTrack(FRawAnimSequenceTrack& RawTrack, int32 NumFrames, 'FName ErrorName, float MaxPosDiff, float MaxAngleDiff)
![image](https://user-images.githubusercontent.com/321692/69853264-5d358c80-12c1-11ea-8365-3bafd3a4afa0.png)

It have to be 'RawTrack.PosKeys.Num() == 1 || RawTrack.PosKeys.Num() == NumFrames', else RawTrack.PosKeys will been removed.

Two ways to resolve it:
1) make sure that: RawTrack.PosKeys.Num() == NumFrames while creating an animsequence
2) do not call CompressRawAnimSequenceTrack (need to change code in ue4).

Thanks very much! @ruyo

**Comment by hamkoo** [comment]
So, I can create a skeletalMesh binding skeleton and animSequence at runtime with c++ code.
![image](https://user-images.githubusercontent.com/321692/69876496-b241c480-12fa-11ea-8e8b-833cf513ef87.png)
