### ISSUE TITLE
UE5 Control Rig

### ISSUE THREAD

**Issue by Tim-McGuinness** [ruyo/VRM4U#78]
Noticed with the latest version for UE5 the control rig widget is not working as intended for models that previously worked with old versions of the plugin in 4.26. 

Mapping seems to be a little all over the place when using the UE5 widget and when porting over working rigs created from the 4.26 widget some components (seemingly hand and foot controls) stop working.

**Comment by ruyo** [comment]
Hi.

Just to confirm, are the bone names in that model standard strings?
In the current UE5EA, the strings that can be used within control rig are strongly restricted.
For example, models that contain multibyte characters cannot be manipulated.
(This is under request to be fixed.)

In my environment, standard models such as VRoid seem to work fine.
If you are comfortable with strings, and your model is publishable, please send me the data and I will look into it.
However, control rig has a lot more restrictions than UE4, so I'm not sure if it can be fixed...

Thanks!

**Comment by Tim-McGuinness** [comment]
Hey There, Just wanted to follow up to say thanks for the pointer! 

Turns out it was spaces instead of underscores ("Left Finger" vs "Left_Finger") in the bone names that was indeed causing the issue and renaming has fixed it.

Might want to add a small mention of this into the documentation as a caveat of UE5 control rigs.
