### ISSUE TITLE
weight error?  (aiVertexWeight::mWeights[i]->mWeight) > 1.0

### ISSUE THREAD

**Issue by hamkoo** [ruyo/VRM4U#8]
After imported with assimp, there'll be
(aiVertexWeight::mWeights[i]->mWeight) > 1.0

What should i do? thanks!

frame=0
![image](https://user-images.githubusercontent.com/321692/69922900-19b66a80-14db-11ea-9973-21e75e2f86b7.png)
frame=32.29
![image](https://user-images.githubusercontent.com/321692/69922907-2f2b9480-14db-11ea-9c68-2054712b9e0f.png)

**Comment by ruyo** [comment]
Hi.
Maybe it's an accuracy error.
UE4 use uint8 for skin weight. So you need to normalize weight sum to 255.
Please search 'InfluenceWeights' in VrmConverModel.cpp.

```
struct FSoftSkinVertexLocal{
	...
	uint8 InfluenceWeights[MAX_TOTAL_INFLUENCES];
	...
};
```

Thanks.

**Comment by hamkoo** [comment]
The range of weight is out [0..1] while importing a .fbx(download from https://www.mixamo.com/) with assimp:
[the range of weight is out [0..1]](https://github.com/assimp/assimp/issues/2800)
Maybe it's an error of assimp.

Was it happend while importing a .vrm file with assimp?

Thanks!~

**Comment by hamkoo** [comment]
@ruyo Thank you very much!~
After normalize weights of vertex, it's well done~

![image](https://user-images.githubusercontent.com/321692/70028099-b7df2900-15de-11ea-9bb3-474f604915e5.png)
