### ISSUE TITLE
High vertex count issue

### ISSUE THREAD

**Issue by apgrjm** [ruyo/VRM4U#9]
![image](https://user-images.githubusercontent.com/14902940/69945612-46936d80-152d-11ea-9096-b95b058968fe.png)

When I load a VRM on UE4 using your plugin, I notice the vertex count is abnormally high.
This was confirmed again on Blender after I exported it from UE4 as an fbx file and load it on Blender, which prevents me from posing it due to extremely low FPS caused by high vertex count.

When I pick one vertex on the hair on Blender, it says it is actually 132 vertices as below:
![image](https://user-images.githubusercontent.com/14902940/69945911-e2bd7480-152d-11ea-9c5b-a89c4adb35e8.png)

Is this a bug? Or Am I missing something?

**Comment by ruyo** [comment]
Hi. 
It is correct data.
You can see vertex count by Windows 3D paint tool. (Rename file test.vrm -> test.glb)
VRoid model has many vertices in data but use a part of them.

You can delete unused vertices if it affects the DCC tool operation.

![image](https://user-images.githubusercontent.com/6472835/69963045-b23c0180-1552-11ea-8506-3c93b53dec5e.png)

Thanks!

**Comment by apgrjm** [comment]
Thanks for your replay. I confirmed that is correct with the same method you used.
The reason why I thought it was abnormal was that the vertex count was around 30,000 when I loaded the same VRM file on Blender using VRM to Blender plugin. But it turned out the plugin reduced the vertex count by removing doubles in the process of loading it.

Thanks again, and keep up the good work!
